In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import re
import nltk
nltk.download('punkt')
nltk.download('stopwords')

print("Required libraries and NLTK data imported successfully.")

Required libraries and NLTK data imported successfully.

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
print("All required libraries and NLTK data have been successfully imported and are ready for use.")

All required libraries and NLTK data have been successfully imported and are ready for use.

The first step is to load the `data.csv` file into a pandas DataFrame from the specified Google Drive path and then display its head to inspect the raw data.

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/data.csv')
print("DataFrame loaded successfully. Displaying the first few rows:")
df.head()

DataFrame loaded successfully. Displaying the first few rows:

,diseases,anxiety_and_nervousness,depression,shortness_of_breath,depressive_or_psychotic_symptoms,sharp_chest_pain,dizziness,insomnia,abnormal_involuntary_movements,chest_tightness,...,stuttering_or_stammering,problems_with_orgasm,nose_deformity,lump_over_jaw,sore_in_nose,hip_weakness,back_swelling,ankle_stiffness_or_tightness,ankle_weakness,neck_weakness
0,panic disorder,1,0,1,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,panic disorder,0,0,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,panic disorder,1,1,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,panic disorder,1,0,0,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,panic disorder,1,1,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0


Since the dataset does not explicitly contain a 'symptom' column but has numerous binary columns representing symptoms, I will first create a 'symptom_text' column by concatenating the names of all present symptoms (where the value is 1) for each row. Then, I will define a text preprocessing function and apply it to this newly created 'symptom_text' column to generate the `cleaned_symptom` column, as specified in the instructions. Finally, I will display the relevant columns to verify the preprocessing.

In [ ]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Re-download NLTK data to ensure it's available for this cell's execution
nltk.download('punkt', quiet=True)
nltk.download('stopwords', quiet=True)
nltk.download('punkt_tab', quiet=True) # Explicitly download 'punkt_tab' as indicated by the error

def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'[^A-z ]', '', text) # Remove punctuation, keeping only letters and spaces
    text = re.sub(r'\d+', '', text)    # Remove numbers
    tokens = word_tokenize(text)
    stop_words = set(stopwords.words('english'))
    filtered_tokens = [word for word in tokens if word not in stop_words]
    return ' '.join(filtered_tokens)

# Identify symptom columns (all columns except 'diseases')
symptom_columns = df.columns.drop('diseases')

# Create a 'symptom_text' column by concatenating symptom names where value is 1
df['symptom_text'] = df.apply(lambda row: ' '.join([col for col in symptom_columns if row[col] == 1]), axis=1)

# Apply the preprocess_text function to the new 'symptom_text' column
df['cleaned_symptom'] = df['symptom_text'].apply(preprocess_text)

print("Original 'symptom_text' column and 'cleaned_symptom' column created. Displaying first few rows:")
df[['diseases', 'symptom_text', 'cleaned_symptom']].head()

Original 'symptom_text' column and 'cleaned_symptom' column created. Displaying first few rows:

,diseases,symptom_text,cleaned_symptom
0,panic disorder,anxiety_and_nervousness shortness_of_breath de...,anxiety_and_nervousness shortness_of_breath de...
1,panic disorder,shortness_of_breath depressive_or_psychotic_sy...,shortness_of_breath depressive_or_psychotic_sy...
2,panic disorder,anxiety_and_nervousness depression shortness_o...,anxiety_and_nervousness depression shortness_o...
3,panic disorder,anxiety_and_nervousness depressive_or_psychoti...,anxiety_and_nervousness depressive_or_psychoti...
4,panic disorder,anxiety_and_nervousness depression insomnia ab...,anxiety_and_nervousness depression insomnia ab...

In [ ]:
from sklearn.preprocessing import LabelEncoder
import collections

# 1. Convert 'diseases' column to numerical labels
label_encoder = LabelEncoder()
df['label'] = label_encoder.fit_transform(df['diseases'])
label_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))

print("Disease labels encoded successfully. Label mapping:")
print(label_mapping)

# 2. Create a vocabulary by tokenizing the 'cleaned_symptom' column
all_words = []
for text in df['cleaned_symptom']:
    all_words.extend(text.split())

word_counts = collections.Counter(all_words)
unique_words = sorted(word_counts.keys())

vocabulary = {"<pad>": 0, "<unk>": 1}
for i, word in enumerate(unique_words):
    vocabulary[word] = i + 2  # Start indexing from 2 after <pad> and <unk>

print(f"\nVocabulary created with {len(vocabulary)} unique words.")
print("First 10 items in vocabulary:", list(vocabulary.items())[:10])

Disease labels encoded successfully. Label mapping:

In [ ]:
import torch
from sklearn.model_selection import train_test_split

# 3. Convert 'cleaned_symptom' to numerical ID sequences and pad
def text_to_sequence(text, vocabulary, max_len):
    words = text.split()
    sequence = [vocabulary.get(word, vocabulary['<unk>']) for word in words]
    if len(sequence) < max_len:
        sequence = sequence + [vocabulary['<pad>']] * (max_len - len(sequence))
    else:
        sequence = sequence[:max_len]
    return sequence

# Using the max_sequence_length identified from previous analysis or setting a reasonable one
# Let's re-calculate max_sequence_length in case it was not explicitly saved or for robustness
symptom_lengths = [len(text.split()) for text in df['cleaned_symptom']]
max_sequence_length = max(symptom_lengths) if symptom_lengths else 0
print(f"Maximum sequence length found: {max_sequence_length}")

# If max_sequence_length is too large, we might want to cap it. Let's cap it at a reasonable value if it exceeds a certain threshold, e.g., 50
# For this dataset, the max length is likely small, but for generality:
# if max_sequence_length > 50:
#     max_sequence_length = 50

X = [text_to_sequence(text, vocabulary, max_sequence_length) for text in df['cleaned_symptom']]
y = df['label'].values

print(f"Converted {len(X)} symptom sequences to numerical IDs and padded to length {max_sequence_length}.")

# 4. Split the dataset into training, validation, and test sets
X_train_val, X_test, y_train_val, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=0.25, random_state=42, stratify=y_train_val) # 0.25 of 0.8 is 0.2

print(f"Dataset split into training: {len(X_train)}, validation: {len(X_val)}, test: {len(X_test)} samples.")

# 5. Convert to PyTorch tensors
X_train = torch.tensor(X_train, dtype=torch.long)
X_val = torch.tensor(X_val, dtype=torch.long)
X_test = torch.tensor(X_test, dtype=torch.long)

y_train = torch.tensor(y_train, dtype=torch.long)
y_val = torch.tensor(y_val, dtype=torch.long)
y_test = torch.tensor(y_test, dtype=torch.long)

print("Features and labels converted to PyTorch tensors.")

print("\nShape of X_train:", X_train.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of X_val:", X_val.shape)
print("Shape of y_val:", y_val.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_test:", y_test.shape)

Maximum sequence length found: 12
Converted 246945 symptom sequences to numerical IDs and padded to length 12.
Dataset split into training: 148167, validation: 49389, test: 49389 samples.
Features and labels converted to PyTorch tensors.

Shape of X_train: torch.Size([148167, 12])
Shape of y_train: torch.Size([148167])
Shape of X_val: torch.Size([49389, 12])
Shape of y_val: torch.Size([49389])
Shape of X_test: torch.Size([49389, 12])
Shape of y_test: torch.Size([49389])

In [ ]:
import torch.nn as nn
import torch.nn.functional as F

# Define the neural network model
class SymptomClassifier(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim, max_seq_len, dropout_prob=0.5):
        super(SymptomClassifier, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim, padding_idx=0) # padding_idx=0 for <pad>
        self.flatten = nn.Flatten()
        # The input dimension to the first linear layer will be max_seq_len * embedding_dim
        self.fc1 = nn.Linear(max_seq_len * embedding_dim, hidden_dim)
        self.bn1 = nn.BatchNorm1d(hidden_dim)
        self.dropout = nn.Dropout(dropout_prob)
        self.fc2 = nn.Linear(hidden_dim, output_dim)

    def forward(self, text):
        # text = [batch size, max_seq_len]
        embedded = self.embedding(text)
        # embedded = [batch size, max_seq_len, embedding_dim]
        flattened = self.flatten(embedded)
        # flattened = [batch size, max_seq_len * embedding_dim]
        x = self.fc1(flattened)
        x = self.bn1(x)
        x = F.relu(x)
        x = self.dropout(x)
        x = self.fc2(x)
        return x

# Model parameters
VOCAB_SIZE = len(vocabulary)
EMBEDDING_DIM = 128
HIDDEN_DIM = 256 # Example hidden dimension
OUTPUT_DIM = len(label_mapping) # Number of unique disease labels
MAX_SEQ_LEN = max_sequence_length # From previous step

# Instantiate the model
model = SymptomClassifier(VOCAB_SIZE, EMBEDDING_DIM, HIDDEN_DIM, OUTPUT_DIM, MAX_SEQ_LEN)

# Print the model architecture and parameter count
print("Model Architecture:")
print(model)

# Count trainable parameters
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f'\nThe model has {count_parameters(model):,} trainable parameters.')

Model Architecture:
SymptomClassifier(
  (embedding): Embedding(330, 128, padding_idx=0)
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (fc1): Linear(in_features=1536, out_features=256, bias=True)
  (bn1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (dropout): Dropout(p=0.5, inplace=False)
  (fc2): Linear(in_features=256, out_features=713, bias=True)
)

The model has 619,465 trainable parameters.

In [ ]:
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader

# 1. Define device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Using device: {device}')

# Move model to device
model.to(device)

# 2. Define hyperparameters
LEARNING_RATE = 0.001
BATCH_SIZE = 64
N_EPOCHS = 30

# 3. Initialize the Adam optimizer
optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)

# 4. Define the loss function
criterion = nn.CrossEntropyLoss()

# 5. Create TensorDatasets and DataLoaders
train_data = TensorDataset(X_train, y_train)
val_data = TensorDataset(X_val, y_val)
test_data = TensorDataset(X_test, y_test)

train_loader = DataLoader(train_data, shuffle=True, batch_size=BATCH_SIZE)
val_loader = DataLoader(val_data, shuffle=False, batch_size=BATCH_SIZE)
test_loader = DataLoader(test_data, shuffle=False, batch_size=BATCH_SIZE)

print(f"DataLoaders created with batch size {BATCH_SIZE}.")

# 6. Implement the training loop
def train(model, iterator, optimizer, criterion, device):
    epoch_loss = 0
    epoch_acc = 0
    model.train() # Set the model to training mode

    for X_batch, y_batch in iterator:
        X_batch = X_batch.to(device)
        y_batch = y_batch.to(device)

        optimizer.zero_grad() # Zero the gradients
        predictions = model(X_batch)
        loss = criterion(predictions, y_batch)

        # Calculate accuracy
        _, predicted_labels = torch.max(predictions, 1)
        correct_predictions = (predicted_labels == y_batch).sum().item()
        accuracy = correct_predictions / y_batch.shape[0]

        loss.backward() # Backpropagate the loss
        optimizer.step() # Update model weights

        epoch_loss += loss.item()
        epoch_acc += accuracy

    return epoch_loss / len(iterator), epoch_acc / len(iterator)

def evaluate(model, iterator, criterion, device):
    epoch_loss = 0
    epoch_acc = 0
    model.eval() # Set the model to evaluation mode

    with torch.no_grad(): # Disable gradient calculations
        for X_batch, y_batch in iterator:
            X_batch = X_batch.to(device)
            y_batch = y_batch.to(device)

            predictions = model(X_batch)
            loss = criterion(predictions, y_batch)

            # Calculate accuracy
            _, predicted_labels = torch.max(predictions, 1)
            correct_predictions = (predicted_labels == y_batch).sum().item()
            accuracy = correct_predictions / y_batch.shape[0]

            epoch_loss += loss.item()
            epoch_acc += accuracy

    return epoch_loss / len(iterator), epoch_acc / len(iterator)

print("Starting training...")

for epoch in range(N_EPOCHS):
    train_loss, train_acc = train(model, train_loader, optimizer, criterion, device)
    val_loss, val_acc = evaluate(model, val_loader, criterion, device)

    print(f'Epoch: {epoch+1:02}')
    print(f'\tTrain Loss: {train_loss:.3f} | Train Acc: {train_acc*100:.2f}%')
    print(f'\tVal. Loss: {val_loss:.3f} | Val. Acc: {val_acc*100:.2f}%')

print("Training complete.")

# Evaluate on test set after training
test_loss, test_acc = evaluate(model, test_loader, criterion, device)
print(f'Test Loss: {test_loss:.3f} | Test Acc: {test_acc*100:.2f}%')

Using device: cuda
DataLoaders created with batch size 64.
Starting training...
Epoch: 01
	Train Loss: 1.457 | Train Acc: 65.92%
	Val. Loss: 0.501 | Val. Acc: 83.41%
Epoch: 02
	Train Loss: 0.655 | Train Acc: 79.49%
	Val. Loss: 0.426 | Val. Acc: 84.49%
Epoch: 03
	Train Loss: 0.573 | Train Acc: 81.37%
	Val. Loss: 0.405 | Val. Acc: 84.78%
Epoch: 04
	Train Loss: 0.532 | Train Acc: 82.29%
	Val. Loss: 0.394 | Val. Acc: 85.10%
Epoch: 05
	Train Loss: 0.498 | Train Acc: 83.10%
	Val. Loss: 0.386 | Val. Acc: 84.71%
Epoch: 06
	Train Loss: 0.476 | Train Acc: 83.50%
	Val. Loss: 0.381 | Val. Acc: 85.18%
Epoch: 07
	Train Loss: 0.455 | Train Acc: 84.08%
	Val. Loss: 0.375 | Val. Acc: 85.13%
Epoch: 08
	Train Loss: 0.442 | Train Acc: 84.32%
	Val. Loss: 0.372 | Val. Acc: 85.12%
Epoch: 09
	Train Loss: 0.427 | Train Acc: 84.71%
	Val. Loss: 0.369 | Val. Acc: 85.39%
Epoch: 10
	Train Loss: 0.416 | Train Acc: 84.98%
	Val. Loss: 0.367 | Val. Acc: 85.35%
Epoch: 11
	Train Loss: 0.406 | Train Acc: 85.29%
	Val. Loss: 0.367 | Val. Acc: 85.22%
Epoch: 12
	Train Loss: 0.397 | Train Acc: 85.45%
	Val. Loss: 0.368 | Val. Acc: 85.40%
Epoch: 13
	Train Loss: 0.391 | Train Acc: 85.62%
	Val. Loss: 0.367 | Val. Acc: 85.07%
Epoch: 14
	Train Loss: 0.383 | Train Acc: 85.76%
	Val. Loss: 0.359 | Val. Acc: 85.39%
Epoch: 15
	Train Loss: 0.377 | Train Acc: 85.97%
	Val. Loss: 0.362 | Val. Acc: 85.17%
Epoch: 16
	Train Loss: 0.371 | Train Acc: 86.13%
	Val. Loss: 0.361 | Val. Acc: 85.31%
Epoch: 17
	Train Loss: 0.366 | Train Acc: 86.22%
	Val. Loss: 0.364 | Val. Acc: 85.27%
Epoch: 18
	Train Loss: 0.362 | Train Acc: 86.33%
	Val. Loss: 0.359 | Val. Acc: 85.36%
Epoch: 19
	Train Loss: 0.358 | Train Acc: 86.36%
	Val. Loss: 0.361 | Val. Acc: 85.31%
Epoch: 20
	Train Loss: 0.353 | Train Acc: 86.61%
	Val. Loss: 0.360 | Val. Acc: 85.33%
Epoch: 21
	Train Loss: 0.350 | Train Acc: 86.75%
	Val. Loss: 0.362 | Val. Acc: 85.36%
Epoch: 22
	Train Loss: 0.345 | Train Acc: 86.81%
	Val. Loss: 0.360 | Val. Acc: 85.34%
Epoch: 23
	Train Loss: 0.342 | Train Acc: 86.86%
	Val. Loss: 0.361 | Val. Acc: 85.27%
Epoch: 24
	Train Loss: 0.339 | Train Acc: 86.87%
	Val. Loss: 0.363 | Val. Acc: 85.37%
Epoch: 25
	Train Loss: 0.337 | Train Acc: 87.03%
	Val. Loss: 0.362 | Val. Acc: 85.33%
Epoch: 26
	Train Loss: 0.335 | Train Acc: 87.07%
	Val. Loss: 0.362 | Val. Acc: 85.15%
Epoch: 27
	Train Loss: 0.331 | Train Acc: 87.24%
	Val. Loss: 0.367 | Val. Acc: 85.19%
Epoch: 28
	Train Loss: 0.330 | Train Acc: 87.21%
	Val. Loss: 0.362 | Val. Acc: 85.21%
Epoch: 29
	Train Loss: 0.326 | Train Acc: 87.30%
	Val. Loss: 0.369 | Val. Acc: 85.15%
Epoch: 30
	Train Loss: 0.326 | Train Acc: 87.28%
	Val. Loss: 0.362 | Val. Acc: 85.15%
Training complete.
Test Loss: 0.363 | Test Acc: 85.51%

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import torch

# Ensure the model is on the correct device
model.to(device)

# Function to get predictions and true labels
def get_predictions_and_labels(model, iterator, device):
    all_labels = []
    all_predictions = []
    model.eval() # Set model to evaluation mode
    with torch.no_grad(): # Disable gradient calculations
        for X_batch, y_batch in iterator:
            X_batch = X_batch.to(device)
            y_batch = y_batch.to(device)

            predictions = model(X_batch)
            _, predicted_labels = torch.max(predictions, 1)

            all_labels.extend(y_batch.cpu().numpy())
            all_predictions.extend(predicted_labels.cpu().numpy())
    return np.array(all_labels), np.array(all_predictions)

# Get true and predicted labels for the test set
y_true, y_pred = get_predictions_and_labels(model, test_loader, device)

print("Evaluating model performance on the test set...")

# 3. Calculate and print overall accuracy
accuracy = accuracy_score(y_true, y_pred)
print(f"\nOverall Test Accuracy: {accuracy:.4f}")

# 4. Generate and print classification report
# We need target names for the classification report, which are the inverse-transformed labels
# label_encoder was defined earlier, OUTPUT_DIM was also defined.
target_names = label_encoder.inverse_transform(range(OUTPUT_DIM))
print("\nClassification Report:")
print(classification_report(y_true, y_pred, target_names=target_names, zero_division=0))

# 5. Compute and display the confusion matrix
cm = confusion_matrix(y_true, y_pred)

# Since there are many classes (OUTPUT_DIM), visualizing the full confusion matrix as a heatmap
# might be too large and unreadable. Instead, we can summarize it or show a partial view.
# For now, we'll just print the shape and a small part of it.
print(f"\nConfusion Matrix (shape {cm.shape}):")
print(cm[:5, :5]) # Displaying a small portion of the confusion matrix

# For visualization, if the number of classes is manageable, e.g., < 50, a heatmap can be useful.
# For 713 classes, it's not practical to visualize directly.
# If we were to visualize for fewer classes or a subset:
# plt.figure(figsize=(15, 12))
# sns.heatmap(cm, annot=False, fmt='d', cmap='Blues')
# plt.xlabel('Predicted Label')
# plt.ylabel('True Label')
# plt.title('Confusion Matrix')
# plt.show()

print("Test set evaluation complete. Classification report and a partial confusion matrix displayed.")

Evaluating model performance on the test set...

Overall Test Accuracy: 0.8551

Classification Report:
                                                          precision    recall  f1-score   support

                                            Rare Disease       0.78      0.55      0.64        33
                               abdominal aortic aneurysm       1.00      1.00      1.00        28
                                        abdominal hernia       0.96      0.98      0.97        81
                                         abscess of nose       0.76      0.88      0.82        58
                                     abscess of the lung       1.00      1.00      1.00         4
                                  abscess of the pharynx       0.83      0.91      0.87        68
                                    acanthosis nigricans       0.67      0.67      0.67         6
                                               acariasis       0.88      1.00      0.93         7
                                               achalasia       0.75      0.88      0.81        17
                                                    acne       0.72      0.76      0.74        99
                                       actinic keratosis       0.88      0.74      0.80       182
                                     acute bronchiolitis       0.98      0.88      0.93       241
                                        acute bronchitis       0.73      0.72      0.73       243
                                      acute bronchospasm       0.58      0.77      0.66       181
                   acute fatty liver of pregnancy (aflp)       0.00      0.00      0.00         2
                                          acute glaucoma       0.26      0.31      0.28        42
                                     acute kidney injury       0.98      0.97      0.98       182
                                      acute otitis media       0.73      0.91      0.81       137
                                      acute pancreatitis       0.88      0.90      0.89       241
              acute respiratory distress syndrome (ards)       0.84      0.93      0.88        90
                                         acute sinusitis       0.79      0.83      0.81       181
                                   acute stress reaction       0.88      0.93      0.90       182
                     adhesive capsulitis of the shoulder       0.79      1.00      0.88        15
                                     adjustment reaction       0.72      0.85      0.78       101
                                         adrenal adenoma       0.70      1.00      0.82         7
                                           alcohol abuse       0.89      0.87      0.88       102
                                    alcohol intoxication       0.95      0.90      0.93        70
                                      alcohol withdrawal       0.86      0.98      0.92       133
                                 alcoholic liver disease       0.96      0.96      0.96        49
                                                 allergy       0.97      0.94      0.96       181
                                      allergy to animals       1.00      1.00      1.00         8
                                                alopecia       0.80      0.81      0.80        68
                                       alzheimer disease       0.91      0.91      0.91        67
                                               amblyopia       1.00      1.00      1.00         9
                     amyotrophic lateral sclerosis (als)       0.92      1.00      0.96        12
                                            anal fissure       0.90      0.84      0.87        45
                                            anal fistula       1.00      0.75      0.86         4
                                                  anemia       0.98      0.97      0.98        66
                    anemia due to chronic kidney disease       1.00      0.80      0.89        10
                                anemia due to malignancy       1.00      1.00      1.00         2
                               anemia of chronic disease       0.78      0.88      0.82         8
                                                  angina       0.91      0.95      0.93       181
                                  ankylosing spondylitis       0.83      0.96      0.89       121
                                                 anxiety       0.96      0.92      0.94       240
                                    aortic valve disease       0.89      0.94      0.92        90
                                                 aphakia       0.00      0.00      0.00         2
                                          aphthous ulcer       0.77      0.98      0.86        49
                                         aplastic anemia       0.93      1.00      0.97        14
                                            appendicitis       0.85      0.83      0.84       181
                                              arrhythmia       0.93      0.71      0.80        52
                                    arthritis of the hip       0.96      0.95      0.96       242
                                   ascending cholangitis       0.78      1.00      0.88        14
                                       asperger syndrome       0.81      0.88      0.85        68
                                           aspergillosis       1.00      1.00      1.00         2
                                                  asthma       0.76      0.80      0.78       181
                                             astigmatism       0.57      0.70      0.63        64
                                             atelectasis       0.85      0.55      0.67        20
                                          athlete's foot       0.58      0.91      0.71        76
                                          atonic bladder       0.77      0.71      0.74        14
                                     atrial fibrillation       0.42      0.36      0.38        14
                                          atrial flutter       0.95      0.85      0.90        48
                                 atrophic skin condition       0.79      0.77      0.78        88
                                      atrophic vaginitis       0.78      0.97      0.86        66
                        atrophy of the corpus cavernosum       0.73      0.89      0.80         9
         attention deficit hyperactivity disorder (adhd)       0.74      0.85      0.79       101
                                                  autism       0.89      0.94      0.91        90
                       autonomic nervous system disorder       0.89      0.94      0.91        17
                                      avascular necrosis       1.00      1.00      1.00         2
                                               balanitis       0.96      1.00      0.98        91
                                              bell palsy       0.96      0.93      0.94       137
                                      benign kidney cyst       0.90      0.85      0.88        41
            benign paroxysmal positional vertical (bppv)       0.97      0.98      0.97        89
                      benign prostatic hyperplasia (bph)       0.95      0.95      0.95       241
                   benign vaginal discharge (leukorrhea)       0.88      0.91      0.90       136
                                        bipolar disorder       0.57      0.61      0.59       133
                                            birth trauma       1.00      1.00      1.00         2
                                          bladder cancer       0.89      0.96      0.92        25
                                        bladder disorder       0.52      0.71      0.60        91
                                     bladder obstruction       0.91      0.91      0.91        68
                                             blepharitis       0.80      0.74      0.77       181
                                           blepharospasm       1.00      1.00      1.00         1
                                             bone cancer       0.82      0.82      0.82        17
                                           bone disorder       1.00      0.94      0.97        51
                             bone spur of the calcaneous       1.00      1.00      1.00         6
                                       brachial neuritis       0.97      0.91      0.94       181
                                            brain cancer       0.97      0.73      0.84        45
                                           breast cancer       0.00      0.00      0.00         1
                                             breast cyst       1.00      1.00      1.00         4
                             breast infection (mastitis)       0.95      0.99      0.97       100
                                            broken tooth       0.94      0.94      0.94        33
                                                  bunion       0.67      1.00      0.80         8
                                                    burn       1.00      0.91      0.95        11
                                                bursitis       0.96      0.98      0.97       242
                                                  callus       0.90      0.83      0.86       103
                               carbon monoxide poisoning       0.81      0.72      0.76        18
                                          cardiac arrest       0.91      0.90      0.91        69
                                          cardiomyopathy       0.78      0.92      0.84        62
                                  carpal tunnel syndrome       0.89      0.96      0.92       179
                                                cataract       0.63      0.73      0.67       121
                                          celiac disease       0.88      0.77      0.82        30
                          cellulitis or abscess of mouth       0.97      1.00      0.98        28
                                 central atherosclerosis       0.50      1.00      0.67         4
                central retinal artery or vein occlusion       0.81      0.93      0.87        14
                                          cerebral edema       1.00      0.86      0.92        21
                                          cerebral palsy       0.97      1.00      0.98        28
                                         cervical cancer       1.00      0.89      0.94        19
                                       cervical disorder       0.90      1.00      0.95         9
                                              cervicitis       0.78      0.94      0.85        77
                                               chalazion       0.86      0.89      0.88       136
                                              chickenpox       0.87      0.95      0.91        21
                                               chlamydia       0.73      0.97      0.83        33
                                           cholecystitis       0.94      0.75      0.84       241
                                     choledocholithiasis       0.95      0.88      0.91        88
                                           cholesteatoma       0.56      0.83      0.67         6
                           chondromalacia of the patella       0.62      0.73      0.67        11
                                         chorioretinitis       0.92      0.80      0.86        15
                                       chronic back pain       0.97      0.95      0.96       180
                                    chronic constipation       0.88      0.80      0.84       183
                                        chronic glaucoma       0.68      0.70      0.69       133
chronic inflammatory demyelinating polyneuropathy (cidp)       0.75      0.75      0.75         4
                                  chronic kidney disease       1.00      0.50      0.67         2
                                       chronic knee pain       0.79      0.63      0.70        30
            chronic obstructive pulmonary disease (copd)       0.73      0.48      0.58       181
                                    chronic otitis media       0.97      0.85      0.90       134
                                   chronic pain disorder       0.86      0.85      0.86       135
                                    chronic pancreatitis       0.93      0.95      0.94        59
                                 chronic rheumatic fever       0.76      0.91      0.83        34
                                       chronic sinusitis       0.83      0.84      0.83       131
                                               cirrhosis       0.96      1.00      0.98        66
                         coagulation (bleeding) disorder       1.00      0.94      0.97        18
                                               cold sore       0.97      0.95      0.96        38
                                           colonic polyp       0.76      0.93      0.83        68
                                       colorectal cancer       0.25      0.33      0.29         3
                                             common cold       0.84      0.87      0.85       181
                          complex regional pain syndrome       0.92      0.85      0.88       243
                                              concussion       0.98      0.97      0.97       238
                                        conduct disorder       0.95      0.85      0.90       136
                                 conductive hearing loss       0.94      0.85      0.89       120
                                 congenital heart defect       1.00      0.71      0.83         7
                        congenital malformation syndrome       1.00      1.00      1.00         3
                                          conjunctivitis       0.90      0.87      0.89       182
                           conjunctivitis due to allergy       0.97      0.86      0.92       243
                          conjunctivitis due to bacteria       0.65      0.90      0.76        31
                             conjunctivitis due to virus       0.72      0.87      0.79       136
                                      contact dermatitis       0.86      0.79      0.82       182
                                     conversion disorder       1.00      1.00      1.00         4
                                        cornea infection       0.89      0.77      0.83       181
                                        corneal abrasion       0.55      0.66      0.60       100
                                        corneal disorder       0.55      0.46      0.50       135
                                coronary atherosclerosis       0.95      0.82      0.88        22
                                     cranial nerve palsy       0.99      0.97      0.98        68
                                           crohn disease       0.78      0.67      0.72        75
                                                   croup       0.90      0.80      0.85       181
                                         crushing injury       1.00      0.77      0.87        13
                                          cryptococcosis       1.00      1.00      1.00         2
                                        cushing syndrome       1.00      0.50      0.67         2
                                      cyst of the eyelid       1.00      1.00      1.00         4
                                         cystic fibrosis       1.00      1.00      1.00         3
                                           cysticercosis       0.88      1.00      0.93         7
                                                cystitis       0.86      0.75      0.80       244
                                     de quervain disease       0.79      0.83      0.81        18
                                         decubitus ulcer       1.00      1.00      1.00         2
                              deep vein thrombosis (dvt)       0.96      0.96      0.96        48
                               degenerative disc disease       0.65      0.85      0.73       182
                                                delirium       0.90      0.88      0.89       120
                                                dementia       0.90      0.84      0.87        68
                                           dental caries       0.94      0.88      0.91       237
                                              depression       0.82      0.62      0.71       182
                          dermatitis due to sun exposure       0.89      0.76      0.82        89
                                developmental disability       0.97      0.93      0.95       182
                                   deviated nasal septum       0.97      0.91      0.94       121
                                      diabetes insipidus       0.50      1.00      0.67         2
                                   diabetic ketoacidosis       0.90      0.91      0.91       135
                          diabetic peripheral neuropathy       0.95      0.92      0.94        90
                                    diabetic retinopathy       0.54      0.56      0.55        91
                                             diaper rash       0.96      0.98      0.97       179
                                dislocation of the ankle       1.00      0.75      0.86         4
                                dislocation of the elbow       0.92      0.71      0.80        17
                               dislocation of the finger       0.44      1.00      0.62         4
                                 dislocation of the foot       1.00      0.75      0.86         4
                                  dislocation of the hip       1.00      1.00      1.00         1
                             dislocation of the shoulder       0.91      0.77      0.83        13
                             dislocation of the vertebra       1.00      0.88      0.93         8
                                dislocation of the wrist       0.89      0.89      0.89         9
                                   dissociative disorder       1.00      0.89      0.94        18
                                          diverticulitis       0.86      0.84      0.85       243
                                          diverticulosis       0.82      0.84      0.83       135
                                           down syndrome       0.92      0.88      0.90        25
                                              drug abuse       0.92      0.83      0.87       121
                               drug abuse (barbiturates)       0.50      0.75      0.60        12
                                    drug abuse (cocaine)       0.72      0.84      0.78        56
                            drug abuse (methamphetamine)       0.86      0.94      0.90        66
                                    drug abuse (opioids)       0.72      0.74      0.73       121
                        drug poisoning due to medication       0.98      0.98      0.98        42
                                           drug reaction       0.99      0.97      0.98       182
                                         drug withdrawal       0.94      0.98      0.96        51
                                dry eye of unknown cause       0.75      0.39      0.51       172
                                             dyshidrosis       1.00      0.82      0.90        17
                                      dysthymic disorder       0.85      0.94      0.89       100
                                         ear drum damage       0.82      0.97      0.89       181
                                       ear wax impaction       0.82      0.85      0.84       136
                                         eating disorder       0.98      0.94      0.96        99

In [ ]:
train_losses_history = []
val_losses_history = []
train_accuracies_history = []
val_accuracies_history = []

for epoch in range(N_EPOCHS):
    train_loss, train_acc = train(model, train_loader, optimizer, criterion, device)
    val_loss, val_acc = evaluate(model, val_loader, criterion, device)

    train_losses_history.append(train_loss)
    val_losses_history.append(val_loss)
    train_accuracies_history.append(train_acc)
    val_accuracies_history.append(val_acc)

    print(f'Epoch: {epoch+1:02}')
    print(f'\tTrain Loss: {train_loss:.3f} | Train Acc: {train_acc*100:.2f}%')
    print(f'\tVal. Loss: {val_loss:.3f} | Val. Acc: {val_acc*100:.2f}%')

Epoch: 01
	Train Loss: 0.322 | Train Acc: 87.41%
	Val. Loss: 0.366 | Val. Acc: 85.16%
Epoch: 02
	Train Loss: 0.321 | Train Acc: 87.47%
	Val. Loss: 0.363 | Val. Acc: 85.12%
Epoch: 03
	Train Loss: 0.318 | Train Acc: 87.54%
	Val. Loss: 0.363 | Val. Acc: 85.21%
Epoch: 04
	Train Loss: 0.315 | Train Acc: 87.65%
	Val. Loss: 0.370 | Val. Acc: 85.20%
Epoch: 05
	Train Loss: 0.314 | Train Acc: 87.70%
	Val. Loss: 0.365 | Val. Acc: 85.14%
Epoch: 06
	Train Loss: 0.314 | Train Acc: 87.70%
	Val. Loss: 0.367 | Val. Acc: 85.20%
Epoch: 07
	Train Loss: 0.313 | Train Acc: 87.77%
	Val. Loss: 0.365 | Val. Acc: 85.22%
Epoch: 08
	Train Loss: 0.311 | Train Acc: 87.80%
	Val. Loss: 0.370 | Val. Acc: 85.07%
Epoch: 09
	Train Loss: 0.309 | Train Acc: 87.83%
	Val. Loss: 0.369 | Val. Acc: 85.16%
Epoch: 10
	Train Loss: 0.308 | Train Acc: 87.85%
	Val. Loss: 0.371 | Val. Acc: 85.06%
Epoch: 11
	Train Loss: 0.306 | Train Acc: 87.94%
	Val. Loss: 0.368 | Val. Acc: 85.03%
Epoch: 12
	Train Loss: 0.305 | Train Acc: 87.99%
	Val. Loss: 0.368 | Val. Acc: 85.12%
Epoch: 13
	Train Loss: 0.303 | Train Acc: 88.03%
	Val. Loss: 0.368 | Val. Acc: 85.16%
Epoch: 14
	Train Loss: 0.303 | Train Acc: 87.91%
	Val. Loss: 0.366 | Val. Acc: 85.19%
Epoch: 15
	Train Loss: 0.301 | Train Acc: 88.13%
	Val. Loss: 0.372 | Val. Acc: 85.04%
Epoch: 16
	Train Loss: 0.300 | Train Acc: 88.16%
	Val. Loss: 0.374 | Val. Acc: 85.00%
Epoch: 17
	Train Loss: 0.297 | Train Acc: 88.16%
	Val. Loss: 0.370 | Val. Acc: 85.16%
Epoch: 18
	Train Loss: 0.299 | Train Acc: 88.20%
	Val. Loss: 0.372 | Val. Acc: 84.98%
Epoch: 19
	Train Loss: 0.297 | Train Acc: 88.26%
	Val. Loss: 0.376 | Val. Acc: 84.90%
Epoch: 20
	Train Loss: 0.297 | Train Acc: 88.26%
	Val. Loss: 0.376 | Val. Acc: 84.91%
Epoch: 21
	Train Loss: 0.294 | Train Acc: 88.32%
	Val. Loss: 0.375 | Val. Acc: 84.98%
Epoch: 22
	Train Loss: 0.294 | Train Acc: 88.29%
	Val. Loss: 0.378 | Val. Acc: 84.90%
Epoch: 23
	Train Loss: 0.294 | Train Acc: 88.37%
	Val. Loss: 0.374 | Val. Acc: 85.06%
Epoch: 24
	Train Loss: 0.292 | Train Acc: 88.35%
	Val. Loss: 0.375 | Val. Acc: 85.05%
Epoch: 25
	Train Loss: 0.290 | Train Acc: 88.38%
	Val. Loss: 0.379 | Val. Acc: 85.05%
Epoch: 26
	Train Loss: 0.289 | Train Acc: 88.52%
	Val. Loss: 0.381 | Val. Acc: 84.92%
Epoch: 27
	Train Loss: 0.288 | Train Acc: 88.53%
	Val. Loss: 0.383 | Val. Acc: 84.96%
Epoch: 28
	Train Loss: 0.288 | Train Acc: 88.53%
	Val. Loss: 0.384 | Val. Acc: 84.90%
Epoch: 29
	Train Loss: 0.289 | Train Acc: 88.44%
	Val. Loss: 0.379 | Val. Acc: 84.94%
Epoch: 30
	Train Loss: 0.286 | Train Acc: 88.59%
	Val. Loss: 0.379 | Val. Acc: 84.85%

In [ ]:
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

trainable_params = count_parameters(model)
print(f"Total number of trainable parameters: {trainable_params:,}")

# Calculate model size in megabytes
# Assuming each parameter is a 32-bit float (4 bytes)
bytes_per_parameter = 4 # for float32
model_size_bytes = trainable_params * bytes_per_parameter
model_size_mb = model_size_bytes / (1024 * 1024)

print(f"Estimated model size: {model_size_mb:.4f} MB")

Total number of trainable parameters: 619,465
Estimated model size: 2.3631 MB

In [ ]:
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader

# 1. Define new hyperparameters
NEW_LEARNING_RATE = 0.0001 # Slightly reduced learning rate
NEW_BATCH_SIZE = 128     # Increased batch size
NEW_EMBEDDING_DIM = 256  # Increased embedding dimension
NEW_HIDDEN_DIM = 512     # Increased hidden dimension
NEW_DROPOUT_PROB = 0.5   # Increased dropout probability
NEW_N_EPOCHS = 35        # Increased number of epochs

print(f"New Hyperparameters:")
print(f"  Learning Rate: {NEW_LEARNING_RATE}")
print(f"  Batch Size: {NEW_BATCH_SIZE}")
print(f"  Embedding Dim: {NEW_EMBEDDING_DIM}")
print(f"  Hidden Dim: {NEW_HIDDEN_DIM}")
print(f"  Dropout Prob: {NEW_DROPOUT_PROB}")
print(f"  Epochs: {NEW_N_EPOCHS}")

# 2. Instantiate a new SymptomClassifier model
# Reuse VOCAB_SIZE, OUTPUT_DIM, MAX_SEQ_LEN from previous steps
new_model = SymptomClassifier(
    VOCAB_SIZE,
    NEW_EMBEDDING_DIM,
    NEW_HIDDEN_DIM,
    OUTPUT_DIM,
    MAX_SEQ_LEN,
    NEW_DROPOUT_PROB
)

# Move new model to device
new_model.to(device)
print(f'New model moved to device: {device}')
print(f'\nThe new model has {count_parameters(new_model):,} trainable parameters.')

# 3. Re-initialize the Adam optimizer with the new model's parameters
new_optimizer = optim.Adam(new_model.parameters(), lr=NEW_LEARNING_RATE)

# Reuse criterion from previous step

# Create new DataLoaders with the new batch size
train_loader_tuned = DataLoader(train_data, shuffle=True, batch_size=NEW_BATCH_SIZE)
val_loader_tuned = DataLoader(val_data, shuffle=False, batch_size=NEW_BATCH_SIZE)
test_loader_tuned = DataLoader(test_data, shuffle=False, batch_size=NEW_BATCH_SIZE)

print(f"New DataLoaders created with batch size {NEW_BATCH_SIZE}.")

# 4. Re-implement the training loop and store metrics
train_losses_history_tuned = []
val_losses_history_tuned = []
train_accuracies_history_tuned = []
val_accuracies_history_tuned = []

print("Starting training with new hyperparameters...")

for epoch in range(NEW_N_EPOCHS):
    train_loss_tuned, train_acc_tuned = train(new_model, train_loader_tuned, new_optimizer, criterion, device)
    val_loss_tuned, val_acc_tuned = evaluate(new_model, val_loader_tuned, criterion, device)

    train_losses_history_tuned.append(train_loss_tuned)
    val_losses_history_tuned.append(val_loss_tuned)
    train_accuracies_history_tuned.append(train_acc_tuned)
    val_accuracies_history_tuned.append(val_acc_tuned)

    print(f'Epoch: {epoch+1:02}')
    print(f'\tTrain Loss: {train_loss_tuned:.3f} | Train Acc: {train_acc_tuned*100:.2f}%')
    print(f'\tVal. Loss: {val_loss_tuned:.3f} | Val. Acc: {val_acc_tuned*100:.2f}%')

print("Training with tuned hyperparameters complete.")

# 5. Evaluate on validation set after retraining
val_loss_final_tuned, val_acc_final_tuned = evaluate(new_model, val_loader_tuned, criterion, device)
print(f'\nFinal Tuned Validation Loss: {val_loss_final_tuned:.3f} | Final Tuned Validation Acc: {val_acc_final_tuned*100:.2f}%')

# 6. Evaluate on test set after retraining
y_true_tuned, y_pred_tuned = get_predictions_and_labels(new_model, test_loader_tuned, device)

print("\nEvaluating model performance on the test set with tuned hyperparameters...")

accuracy_tuned = accuracy_score(y_true_tuned, y_pred_tuned)
print(f"\nOverall Tuned Test Accuracy: {accuracy_tuned:.4f}")

print("\nClassification Report (Tuned Model):")
print(classification_report(y_true_tuned, y_pred_tuned, target_names=target_names, zero_division=0))

print("Hyperparameter tuning and re-evaluation complete.")

New Hyperparameters:
  Learning Rate: 0.0001
  Batch Size: 128
  Embedding Dim: 256
  Hidden Dim: 512
  Dropout Prob: 0.5
  Epochs: 35
New model moved to device: cuda

The new model has 2,024,649 trainable parameters.
New DataLoaders created with batch size 128.
Starting training with new hyperparameters...
Epoch: 01
	Train Loss: 3.148 | Train Acc: 47.24%
	Val. Loss: 1.417 | Val. Acc: 74.91%
Epoch: 02
	Train Loss: 1.096 | Train Acc: 76.99%
	Val. Loss: 0.708 | Val. Acc: 82.52%
Epoch: 03
	Train Loss: 0.688 | Train Acc: 82.33%
	Val. Loss: 0.522 | Val. Acc: 84.48%
Epoch: 04
	Train Loss: 0.554 | Train Acc: 83.77%
	Val. Loss: 0.452 | Val. Acc: 84.78%
Epoch: 05
	Train Loss: 0.488 | Train Acc: 84.68%
	Val. Loss: 0.420 | Val. Acc: 85.12%
Epoch: 06
	Train Loss: 0.452 | Train Acc: 85.18%
	Val. Loss: 0.401 | Val. Acc: 85.22%
Epoch: 07
	Train Loss: 0.430 | Train Acc: 85.54%
	Val. Loss: 0.389 | Val. Acc: 85.28%
Epoch: 08
	Train Loss: 0.411 | Train Acc: 85.90%
	Val. Loss: 0.382 | Val. Acc: 85.51%
Epoch: 09
	Train Loss: 0.398 | Train Acc: 86.12%
	Val. Loss: 0.378 | Val. Acc: 85.40%
Epoch: 10
	Train Loss: 0.388 | Train Acc: 86.36%
	Val. Loss: 0.373 | Val. Acc: 85.35%
Epoch: 11
	Train Loss: 0.379 | Train Acc: 86.58%
	Val. Loss: 0.373 | Val. Acc: 85.35%
Epoch: 12
	Train Loss: 0.370 | Train Acc: 86.77%
	Val. Loss: 0.372 | Val. Acc: 85.46%
Epoch: 13
	Train Loss: 0.366 | Train Acc: 86.80%
	Val. Loss: 0.370 | Val. Acc: 85.24%
Epoch: 14
	Train Loss: 0.357 | Train Acc: 87.00%
	Val. Loss: 0.369 | Val. Acc: 85.37%
Epoch: 15
	Train Loss: 0.354 | Train Acc: 87.15%
	Val. Loss: 0.368 | Val. Acc: 85.25%
Epoch: 16
	Train Loss: 0.350 | Train Acc: 87.20%
	Val. Loss: 0.369 | Val. Acc: 85.19%
Epoch: 17
	Train Loss: 0.343 | Train Acc: 87.36%
	Val. Loss: 0.370 | Val. Acc: 85.17%
Epoch: 18
	Train Loss: 0.339 | Train Acc: 87.49%
	Val. Loss: 0.370 | Val. Acc: 85.09%
Epoch: 19
	Train Loss: 0.335 | Train Acc: 87.61%
	Val. Loss: 0.369 | Val. Acc: 85.20%
Epoch: 20
	Train Loss: 0.332 | Train Acc: 87.63%
	Val. Loss: 0.369 | Val. Acc: 85.26%
Epoch: 21
	Train Loss: 0.328 | Train Acc: 87.76%
	Val. Loss: 0.371 | Val. Acc: 85.09%
Epoch: 22
	Train Loss: 0.326 | Train Acc: 87.79%
	Val. Loss: 0.370 | Val. Acc: 85.06%
Epoch: 23
	Train Loss: 0.322 | Train Acc: 87.94%
	Val. Loss: 0.371 | Val. Acc: 85.11%
Epoch: 24
	Train Loss: 0.318 | Train Acc: 88.04%
	Val. Loss: 0.371 | Val. Acc: 84.99%
Epoch: 25
	Train Loss: 0.316 | Train Acc: 88.13%
	Val. Loss: 0.372 | Val. Acc: 85.08%
Epoch: 26
	Train Loss: 0.313 | Train Acc: 88.22%
	Val. Loss: 0.374 | Val. Acc: 84.91%
Epoch: 27
	Train Loss: 0.311 | Train Acc: 88.12%
	Val. Loss: 0.372 | Val. Acc: 85.05%
Epoch: 28
	Train Loss: 0.309 | Train Acc: 88.29%
	Val. Loss: 0.376 | Val. Acc: 84.84%
Epoch: 29
	Train Loss: 0.305 | Train Acc: 88.38%
	Val. Loss: 0.375 | Val. Acc: 84.95%
Epoch: 30
	Train Loss: 0.305 | Train Acc: 88.45%
	Val. Loss: 0.376 | Val. Acc: 85.02%
Epoch: 31
	Train Loss: 0.301 | Train Acc: 88.44%
	Val. Loss: 0.377 | Val. Acc: 84.91%
Epoch: 32
	Train Loss: 0.300 | Train Acc: 88.55%
	Val. Loss: 0.378 | Val. Acc: 84.91%
Epoch: 33
	Train Loss: 0.299 | Train Acc: 88.46%
	Val. Loss: 0.378 | Val. Acc: 84.95%
Epoch: 34
	Train Loss: 0.295 | Train Acc: 88.61%
	Val. Loss: 0.380 | Val. Acc: 84.88%
Epoch: 35
	Train Loss: 0.294 | Train Acc: 88.65%
	Val. Loss: 0.379 | Val. Acc: 84.93%
Training with tuned hyperparameters complete.

Final Tuned Validation Loss: 0.379 | Final Tuned Validation Acc: 84.93%

Evaluating model performance on the test set with tuned hyperparameters...

Overall Tuned Test Accuracy: 0.8494

Classification Report (Tuned Model):
                                                          precision    recall  f1-score   support

                                            Rare Disease       0.63      0.58      0.60        33
                               abdominal aortic aneurysm       0.90      1.00      0.95        28
                                        abdominal hernia       0.94      0.98      0.96        81
                                         abscess of nose       0.85      0.88      0.86        58
                                     abscess of the lung       1.00      1.00      1.00         4
                                  abscess of the pharynx       0.81      0.94      0.87        68
                                    acanthosis nigricans       0.60      0.50      0.55         6
                                               acariasis       1.00      0.71      0.83         7
                                               achalasia       0.81      0.76      0.79        17
                                                    acne       0.74      0.75      0.74        99
                                       actinic keratosis       0.82      0.74      0.78       182
                                     acute bronchiolitis       0.92      0.88      0.90       241
                                        acute bronchitis       0.79      0.65      0.71       243
                                      acute bronchospasm       0.60      0.76      0.67       181
                   acute fatty liver of pregnancy (aflp)       0.67      1.00      0.80         2
                                          acute glaucoma       0.34      0.50      0.41        42
                                     acute kidney injury       0.97      0.97      0.97       182
                                      acute otitis media       0.76      0.76      0.76       137
                                      acute pancreatitis       0.91      0.86      0.89       241
              acute respiratory distress syndrome (ards)       0.84      0.92      0.88        90
                                         acute sinusitis       0.78      0.84      0.81       181
                                   acute stress reaction       0.85      0.91      0.88       182
                     adhesive capsulitis of the shoulder       0.79      1.00      0.88        15
                                     adjustment reaction       0.78      0.80      0.79       101
                                         adrenal adenoma       0.88      1.00      0.93         7
                                           alcohol abuse       0.92      0.84      0.88       102
                                    alcohol intoxication       0.93      0.93      0.93        70
                                      alcohol withdrawal       0.92      0.95      0.94       133
                                 alcoholic liver disease       0.94      0.96      0.95        49
                                                 allergy       0.96      0.93      0.95       181
                                      allergy to animals       1.00      1.00      1.00         8
                                                alopecia       0.74      0.88      0.81        68
                                       alzheimer disease       1.00      0.91      0.95        67
                                               amblyopia       1.00      1.00      1.00         9
                     amyotrophic lateral sclerosis (als)       1.00      1.00      1.00        12
                                            anal fissure       0.90      0.84      0.87        45
                                            anal fistula       1.00      0.75      0.86         4
                                                  anemia       0.97      0.98      0.98        66
                    anemia due to chronic kidney disease       1.00      0.80      0.89        10
                                anemia due to malignancy       0.67      1.00      0.80         2
                               anemia of chronic disease       0.78      0.88      0.82         8
                                                  angina       0.92      0.94      0.93       181
                                  ankylosing spondylitis       0.84      0.93      0.88       121
                                                 anxiety       0.94      0.91      0.92       240
                                    aortic valve disease       0.89      0.93      0.91        90
                                                 aphakia       0.00      0.00      0.00         2
                                          aphthous ulcer       0.87      0.96      0.91        49
                                         aplastic anemia       0.93      1.00      0.97        14
                                            appendicitis       0.79      0.83      0.81       181
                                              arrhythmia       0.94      0.63      0.76        52
                                    arthritis of the hip       0.97      0.95      0.96       242
                                   ascending cholangitis       0.93      1.00      0.97        14
                                       asperger syndrome       0.81      0.87      0.84        68
                                           aspergillosis       1.00      1.00      1.00         2
                                                  asthma       0.79      0.73      0.76       181
                                             astigmatism       0.53      0.73      0.61        64
                                             atelectasis       0.79      0.55      0.65        20
                                          athlete's foot       0.74      0.78      0.76        76
                                          atonic bladder       0.77      0.71      0.74        14
                                     atrial fibrillation       0.62      0.36      0.45        14
                                          atrial flutter       0.80      0.94      0.87        48
                                 atrophic skin condition       0.76      0.76      0.76        88
                                      atrophic vaginitis       0.83      0.89      0.86        66
                        atrophy of the corpus cavernosum       0.73      0.89      0.80         9
         attention deficit hyperactivity disorder (adhd)       0.82      0.81      0.82       101
                                                  autism       0.92      0.91      0.92        90
                       autonomic nervous system disorder       0.89      0.94      0.91        17
                                      avascular necrosis       1.00      1.00      1.00         2
                                               balanitis       0.96      0.98      0.97        91
                                              bell palsy       0.93      0.93      0.93       137
                                      benign kidney cyst       0.90      0.88      0.89        41
            benign paroxysmal positional vertical (bppv)       0.97      0.98      0.97        89
                      benign prostatic hyperplasia (bph)       0.96      0.95      0.95       241
                   benign vaginal discharge (leukorrhea)       0.82      0.93      0.87       136
                                        bipolar disorder       0.54      0.60      0.57       133
                                            birth trauma       1.00      1.00      1.00         2
                                          bladder cancer       0.86      0.96      0.91        25
                                        bladder disorder       0.51      0.75      0.60        91
                                     bladder obstruction       0.93      0.93      0.93        68
                                             blepharitis       0.84      0.70      0.77       181
                                           blepharospasm       1.00      1.00      1.00         1
                                             bone cancer       0.94      1.00      0.97        17
                                           bone disorder       0.94      0.94      0.94        51
                             bone spur of the calcaneous       1.00      1.00      1.00         6
                                       brachial neuritis       0.95      0.92      0.94       181
                                            brain cancer       0.87      0.76      0.81        45
                                           breast cancer       0.00      0.00      0.00         1
                                             breast cyst       1.00      1.00      1.00         4
                             breast infection (mastitis)       0.95      0.98      0.97       100
                                            broken tooth       1.00      0.88      0.94        33
                                                  bunion       0.67      1.00      0.80         8
                                                    burn       1.00      0.91      0.95        11
                                                bursitis       0.97      0.98      0.98       242
                                                  callus       0.86      0.84      0.85       103
                               carbon monoxide poisoning       0.81      0.72      0.76        18
                                          cardiac arrest       0.85      0.90      0.87        69
                                          cardiomyopathy       0.92      0.89      0.90        62
                                  carpal tunnel syndrome       0.91      0.94      0.93       179
                                                cataract       0.70      0.71      0.71       121
                                          celiac disease       0.80      0.80      0.80        30
                          cellulitis or abscess of mouth       0.97      1.00      0.98        28
                                 central atherosclerosis       0.67      1.00      0.80         4
                central retinal artery or vein occlusion       0.68      0.93      0.79        14
                                          cerebral edema       0.86      0.86      0.86        21
                                          cerebral palsy       0.90      1.00      0.95        28
                                         cervical cancer       1.00      0.89      0.94        19
                                       cervical disorder       0.90      1.00      0.95         9
                                              cervicitis       0.78      0.90      0.83        77
                                               chalazion       0.85      0.90      0.88       136
                                              chickenpox       0.95      0.90      0.93        21
                                               chlamydia       0.73      0.97      0.83        33
                                           cholecystitis       0.77      0.88      0.82       241
                                     choledocholithiasis       0.92      0.90      0.91        88
                                           cholesteatoma       0.56      0.83      0.67         6
                           chondromalacia of the patella       0.67      0.55      0.60        11
                                         chorioretinitis       0.92      0.80      0.86        15
                                       chronic back pain       0.94      0.95      0.95       180
                                    chronic constipation       0.88      0.81      0.84       183
                                        chronic glaucoma       0.64      0.76      0.69       133
chronic inflammatory demyelinating polyneuropathy (cidp)       0.67      1.00      0.80         4
                                  chronic kidney disease       1.00      0.50      0.67         2
                                       chronic knee pain       0.83      0.63      0.72        30
            chronic obstructive pulmonary disease (copd)       0.62      0.67      0.64       181
                                    chronic otitis media       0.86      0.92      0.89       134
                                   chronic pain disorder       0.84      0.87      0.86       135
                                    chronic pancreatitis       0.90      0.95      0.93        59
                                 chronic rheumatic fever       0.79      0.88      0.83        34
                                       chronic sinusitis       0.82      0.81      0.82       131
                                               cirrhosis       0.98      0.98      0.98        66
                         coagulation (bleeding) disorder       1.00      0.94      0.97        18
                                               cold sore       0.97      0.95      0.96        38
                                           colonic polyp       0.86      0.88      0.87        68
                                       colorectal cancer       0.25      0.33      0.29         3
                                             common cold       0.83      0.87      0.85       181
                          complex regional pain syndrome       0.90      0.83      0.86       243
                                              concussion       0.97      0.97      0.97       238
                                        conduct disorder       0.94      0.88      0.90       136
                                 conductive hearing loss       0.94      0.85      0.89       120
                                 congenital heart defect       1.00      0.71      0.83         7
                        congenital malformation syndrome       1.00      1.00      1.00         3
                                          conjunctivitis       0.91      0.86      0.88       182
                           conjunctivitis due to allergy       0.86      0.88      0.87       243
                          conjunctivitis due to bacteria       0.89      0.77      0.83        31
                             conjunctivitis due to virus       0.74      0.85      0.79       136
                                      contact dermatitis       0.77      0.80      0.78       182
                                     conversion disorder       1.00      1.00      1.00         4
                                        cornea infection       0.87      0.78      0.82       181
                                        corneal abrasion       0.65      0.50      0.56       100
                                        corneal disorder       0.48      0.41      0.44       135
                                coronary atherosclerosis       0.79      0.86      0.83        22
                                     cranial nerve palsy       1.00      0.93      0.96        68
                                           crohn disease       0.79      0.67      0.72        75
                                                   croup       0.90      0.78      0.84       181
                                         crushing injury       0.83      0.77      0.80        13
                                          cryptococcosis       1.00      1.00      1.00         2
                                        cushing syndrome       1.00      0.50      0.67         2
                                      cyst of the eyelid       1.00      1.00      1.00         4
                                         cystic fibrosis       1.00      1.00      1.00         3
                                           cysticercosis       0.67      0.86      0.75         7
                                                cystitis       0.81      0.78      0.79       244
                                     de quervain disease       0.81      0.72      0.76        18
                                         decubitus ulcer       1.00      0.50      0.67         2
                              deep vein thrombosis (dvt)       0.90      0.96      0.93        48
                               degenerative disc disease       0.71      0.73      0.72       182
                                                delirium       0.90      0.88      0.89       120
                                                dementia       0.83      0.88      0.86        68

In [ ]:
import torch

# Define the path to save the model
model_save_path = 'tuned_symptom_classifier_model.pth'

# Save the state dictionary of the new_model
torch.save(new_model.state_dict(), model_save_path)

print(f"Model state dictionary saved successfully to: {model_save_path}")

Model state dictionary saved successfully to: tuned_symptom_classifier_model.pth

In [ ]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import torch
import torch.nn as nn
import torch.nn.functional as F

# Ensure NLTK data is downloaded for the preprocessing function
nltk.download('punkt', quiet=True)
nltk.download('stopwords', quiet=True)
nltk.download('punkt_tab', quiet=True)

# Define the neural network model (copied from cell a005c9eb to ensure it's available)
class SymptomClassifier(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim, max_seq_len, dropout_prob=0.5):
        super(SymptomClassifier, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim, padding_idx=0)
        self.flatten = nn.Flatten()
        self.fc1 = nn.Linear(max_seq_len * embedding_dim, hidden_dim)
        self.bn1 = nn.BatchNorm1d(hidden_dim)
        self.dropout = nn.Dropout(dropout_prob)
        self.fc2 = nn.Linear(hidden_dim, output_dim)

    def forward(self, text):
        embedded = self.embedding(text)
        flattened = self.flatten(embedded)
        x = self.fc1(flattened)
        x = self.bn1(x)
        x = F.relu(x)
        x = self.dropout(x)
        x = self.fc2(x)
        return x

# Model parameters (ensure these match the parameters used for the tuned model)
# These variables were defined in previous cells and are available in the kernel state
VOCAB_SIZE_LOADED = VOCAB_SIZE
EMBEDDING_DIM_LOADED = NEW_EMBEDDING_DIM # Use NEW_EMBEDDING_DIM from tuned model
HIDDEN_DIM_LOADED = NEW_HIDDEN_DIM      # Use NEW_HIDDEN_DIM from tuned model
OUTPUT_DIM_LOADED = OUTPUT_DIM
MAX_SEQ_LEN_LOADED = MAX_SEQ_LEN
DROPOUT_PROB_LOADED = NEW_DROPOUT_PROB # Use NEW_DROPOUT_PROB from tuned model

# Instantiate the model
loaded_model = SymptomClassifier(
    VOCAB_SIZE_LOADED,
    EMBEDDING_DIM_LOADED,
    HIDDEN_DIM_LOADED,
    OUTPUT_DIM_LOADED,
    MAX_SEQ_LEN_LOADED,
    DROPOUT_PROB_LOADED
)

# Define the path to the saved model
model_save_path = 'tuned_symptom_classifier_model.pth'

# Load the state dictionary
# Ensure 'device' is defined from previous cells (e.g., device = torch.device('cuda' if torch.cuda.is_available() else 'cpu'))
loaded_model.load_state_dict(torch.load(model_save_path, map_location=torch.device('cpu')))

# Move the loaded model to the correct device (CPU or CUDA) before inference
loaded_model.to(device)

# Set the model to evaluation mode (important for inference)
loaded_model.eval()

print("Model loaded successfully!")

# Sample input for testing
sample_symptom_text = "anxiety, shortness of breath, depressive symptoms, chest tightness, palpitations"

# 1. Preprocess the sample input (using the preprocess_text function defined earlier in cell 904e656d)
# Ensure the preprocess_text function is available in the environment, or re-define it if necessary.
# For safety, I'll include it again here, though it should be in the global scope from previous execution.


def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'[^A-z ]', '', text) # Remove punctuation, keeping only letters and spaces
    text = re.sub(r'\d+', '', text)    # Remove numbers
    tokens = word_tokenize(text)
    stop_words = set(stopwords.words('english'))
    filtered_tokens = [word for word in tokens if word not in stop_words]
    return ' '.join(filtered_tokens)

cleaned_sample_text = preprocess_text(sample_symptom_text)
print(f"Original sample: '{sample_symptom_text}'")
print(f"Cleaned sample:  '{cleaned_sample_text}'")

# 2. Convert to numerical ID sequence and pad
# Ensure vocabulary and MAX_SEQ_LEN are available
# MAX_SEQ_LEN was determined in df83f4ce, vocabulary in d5240566

def text_to_sequence_inference(text, vocabulary, max_len):
    words = text.split()
    sequence = [vocabulary.get(word, vocabulary['<unk>']) for word in words]
    if len(sequence) < max_len:
        sequence = sequence + [vocabulary['<pad>']] * (max_len - len(sequence))
    else:
        sequence = sequence[:max_len]
    return sequence

# Using MAX_SEQ_LEN from the training process, which is MAX_SEQ_LEN (12)
processed_sequence = text_to_sequence_inference(cleaned_sample_text, vocabulary, MAX_SEQ_LEN)
print(f"Processed sequence: {processed_sequence}")

# 3. Convert to PyTorch tensor
input_tensor = torch.tensor(processed_sequence, dtype=torch.long).unsqueeze(0) # Add batch dimension
print(f"Input tensor shape: {input_tensor.shape}")

# 4. Move input to the same device as the model
input_tensor = input_tensor.to(device)

# 5. Get prediction from the loaded model
# loaded_model.eval() # Ensure model is in evaluation mode - already set above during loading
with torch.no_grad():
    output = loaded_model(input_tensor)
    probabilities = F.softmax(output, dim=1)
    predicted_label_id = torch.argmax(probabilities, dim=1).item()

# 6. Interpret the prediction
predicted_disease = label_encoder.inverse_transform([predicted_label_id])[0]

print(f"\nPredicted Disease ID: {predicted_label_id}")
print(f"Predicted Disease: {predicted_disease}")

Model loaded successfully!
Original sample: 'anxiety, shortness of breath, depressive symptoms, chest tightness, palpitations'
Cleaned sample:  'anxiety shortness breath depressive symptoms chest tightness palpitations'
Processed sequence: [1, 1, 1, 1, 1, 1, 1, 221, 0, 0, 0, 0]
Input tensor shape: torch.Size([1, 12])

Predicted Disease ID: 270
Predicted Disease: gastrointestinal hemorrhage

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# Redefine the model architecture exactly as it was during training
class SymptomClassifier(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim, max_seq_len, dropout_prob=0.5):
        super(SymptomClassifier, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim, padding_idx=0)
        self.flatten = nn.Flatten()
        self.fc1 = nn.Linear(max_seq_len * embedding_dim, hidden_dim)
        self.bn1 = nn.BatchNorm1d(hidden_dim)
        self.dropout = nn.Dropout(p=dropout_prob)
        self.fc2 = nn.Linear(hidden_dim, output_dim)

    def forward(self, text):
        embedded = self.embedding(text)
        flattened = self.flatten(embedded)
        x = self.fc1(flattened)
        x = self.bn1(x)
        x = F.relu(x)
        x = self.dropout(x)
        x = self.fc2(x)
        return x

# Model parameters (ensure these match the parameters used for the tuned model)
# These variables were defined in previous cells and are available in the kernel state
VOCAB_SIZE_LOADED = VOCAB_SIZE
EMBEDDING_DIM_LOADED = NEW_EMBEDDING_DIM # Use NEW_EMBEDDING_DIM from tuned model
HIDDEN_DIM_LOADED = NEW_HIDDEN_DIM      # Use NEW_HIDDEN_DIM from tuned model
OUTPUT_DIM_LOADED = OUTPUT_DIM
MAX_SEQ_LEN_LOADED = MAX_SEQ_LEN
DROPOUT_PROB_LOADED = NEW_DROPOUT_PROB # Use NEW_DROPOUT_PROB from tuned model

# Instantiate the model
loaded_model = SymptomClassifier(
    VOCAB_SIZE_LOADED,
    EMBEDDING_DIM_LOADED,
    HIDDEN_DIM_LOADED,
    OUTPUT_DIM_LOADED,
    MAX_SEQ_LEN_LOADED,
    DROPOUT_PROB_LOADED
)

# Define the path to the saved model
model_save_path = 'tuned_symptom_classifier_model.pth'

# Load the state dictionary
loaded_model.load_state_dict(torch.load(model_save_path, map_location=torch.device('cpu')))

# Move the loaded model to the correct device (CPU or CUDA)
loaded_model.to(device)

# Set the model to evaluation mode (important for inference)
loaded_model.eval()

print("Model loaded successfully!")
print("Loaded Model Architecture:")
print(loaded_model)

Model loaded successfully!
Loaded Model Architecture:
SymptomClassifier(
  (embedding): Embedding(330, 256, padding_idx=0)
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (fc1): Linear(in_features=3072, out_features=512, bias=True)
  (bn1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (dropout): Dropout(p=0.5, inplace=False)
  (fc2): Linear(in_features=512, out_features=713, bias=True)
)

In [ ]:
# Sample input for a more common disease (e.g., Allergy) using snake_case terms
sample_symptom_text_common = "allergic_reaction, nasal_congestion, cough, sore_throat, runny_nose, itchy_eyes"

print(f"Original sample: '{sample_symptom_text_common}'")

# 1. Preprocess the sample input using the existing function
cleaned_sample_text_common = preprocess_text(sample_symptom_text_common)
print(f"Cleaned sample:  '{cleaned_sample_text_common}'")

# 2. Convert to numerical ID sequence and pad
processed_sequence_common = text_to_sequence_inference(cleaned_sample_text_common, vocabulary, MAX_SEQ_LEN)
print(f"Processed sequence: {processed_sequence_common}")

# 3. Convert to PyTorch tensor
input_tensor_common = torch.tensor(processed_sequence_common, dtype=torch.long).unsqueeze(0) # Add batch dimension
print(f"Input tensor shape: {input_tensor_common.shape}")

# 4. Move input to the same device as the model
input_tensor_common = input_tensor_common.to(device)

# 5. Get prediction from the loaded model
loaded_model.eval() # Ensure model is in evaluation mode
with torch.no_grad():
    output_common = loaded_model(input_tensor_common)
    probabilities_common = F.softmax(output_common, dim=1)
    predicted_label_id_common = torch.argmax(probabilities_common, dim=1).item()

# 6. Interpret the prediction
predicted_disease_common = label_encoder.inverse_transform([predicted_label_id_common])[0]

print(f"\nPredicted Disease ID: {predicted_label_id_common}")
print(f"Predicted Disease: {predicted_disease_common}")

Original sample: 'allergic_reaction, nasal_congestion, cough, sore_throat, runny_nose, itchy_eyes'
Cleaned sample:  'allergic_reaction nasal_congestion cough sore_throat runny_nose itchy_eyes'
Processed sequence: [11, 201, 51, 277, 1, 1, 0, 0, 0, 0, 0, 0]
Input tensor shape: torch.Size([1, 12])

Predicted Disease ID: 122
Predicted Disease: chronic obstructive pulmonary disease (copd)

In [ ]:
disease_counts = df['diseases'].value_counts()

print("--- Disease Class Distribution Analysis ---")

# 1. Get the value counts of the `diseases` column and 2. Sort these counts in ascending order
sorted_disease_counts = disease_counts.sort_values(ascending=True)

# 3. Print the total number of unique diseases
total_unique_diseases = len(disease_counts)
print(f"Total number of unique diseases: {total_unique_diseases}")

# 4. Print the minimum, maximum, and average occurrences of diseases
min_occurrence = disease_counts.min()
max_occurrence = disease_counts.max()
avg_occurrence = disease_counts.mean()
print(f"Minimum disease occurrence: {min_occurrence}")
print(f"Maximum disease occurrence: {max_occurrence}")
print(f"Average disease occurrence: {avg_occurrence:.2f}")

# 5. Display the top 20 most frequent diseases
print("\nTop 20 Most Frequent Diseases:")
print(disease_counts.head(20).to_string())

# 6. Display the bottom 20 least frequent diseases (low-support classes)
print("\nBottom 20 Least Frequent Diseases (Low-Support Classes):")
print(sorted_disease_counts.head(20).to_string())

--- Disease Class Distribution Analysis ---
Total number of unique diseases: 713
Minimum disease occurrence: 6
Maximum disease occurrence: 1219
Average disease occurrence: 346.35

Top 20 Most Frequent Diseases:
diseases
cystitis                          1219
vulvodynia                        1218
nose disorder                     1218
complex regional pain syndrome    1217
spondylosis                       1216
vaginal cyst                      1215
conjunctivitis due to allergy     1215
esophagitis                       1215
peripheral nerve disorder         1215
hypoglycemia                      1215
gastrointestinal hemorrhage       1214
diverticulitis                    1214
acute bronchitis                  1213
pneumonia                         1212
spontaneous abortion              1212
fungal infection of the hair      1212
sprain or strain                  1212
infectious gastroenteritis        1212
gout                              1211
strep throat                      1210

Bottom 20 Least Frequent Diseases (Low-Support Classes):
diseases
g6pd enzyme deficiency                            6
pinguecula                                        6
edward syndrome                                   6
breast cancer                                     6
wernicke korsakoff syndrome                       6
tuberous sclerosis                                6
dislocation of the hip                            6
priapism                                          6
hypertrophic obstructive cardiomyopathy (hocm)    6
empyema                                           6
vulvar cancer                                     6
blepharospasm                                     6
omphalitis                                        7
fetal alcohol syndrome                            7
pemphigus                                         7
injury to the finger                              7
open wound from surgical incision                 7
spinocerebellar ataxia                            8
hypercholesterolemia                              8
fracture of the finger                            8

In [ ]:
import numpy as np
from sklearn.utils import class_weight

# 1. Calculate class weights for nn.CrossEntropyLoss based on the inverse frequency
# Get the unique classes and their counts from the training set labels (y_train)
# Using sklearn's compute_class_weight to get balanced weights
class_weights_array = class_weight.compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train.cpu().numpy()), # Ensure all classes are covered
    y=y_train.cpu().numpy()
)

# Map the weights to the original label IDs
# The compute_class_weight returns weights in the order of sorted unique classes
# We need to create a full weight tensor indexed by the original label IDs (0 to OUTPUT_DIM-1)
full_class_weights = np.zeros(OUTPUT_DIM)
unique_classes_in_train = np.unique(y_train.cpu().numpy())
for i, class_label in enumerate(unique_classes_in_train):
    full_class_weights[class_label] = class_weights_array[i]

# 2. Convert these class weights into a PyTorch tensor and move it to the appropriate device
class_weights_tensor = torch.tensor(full_class_weights, dtype=torch.float).to(device)

print("Calculated class weights:")
print(class_weights_tensor)
print(f"Shape of class weights tensor: {class_weights_tensor.shape}")

Calculated class weights:
tensor([ 2.0575,  2.5037,  0.8517,  1.1943, 18.8916,  1.0137, 11.5449,  9.4458,
         4.1562,  0.6973,  0.3813,  0.2878,  0.2858,  0.3820, 41.5616,  1.6493,
         0.3820,  0.5068,  0.2866,  0.7668,  0.3820,  0.3806,  4.7229,  0.6904,
         9.8956,  0.6791,  0.9849,  0.5208,  1.4041,  0.3827,  9.0351,  1.0187,
         1.0288,  7.1658,  5.7724,  1.5280, 17.3173,  1.0443,  6.9269, 29.6868,
         8.6587,  0.3820,  0.5709,  0.2890,  0.7668, 41.5616,  1.4233,  4.9478,
         0.3841,  1.3494,  0.2862,  4.7229,  1.0237, 34.6346,  0.3834,  1.0767,
         3.5222,  0.9075,  4.8327,  5.0685,  1.4431,  0.7901,  1.0549,  7.1658,
         0.6813,  0.7668,  4.1562, 34.6346,  0.7640,  0.5056,  1.6759,  0.7812,
         0.2870,  0.5068,  0.5234, 29.6868,  2.7708,  0.7640,  1.0237,  0.3820,
        51.9520,  4.1562,  1.3582, 10.9373,  0.3813,  1.5168, 51.9520, 14.8434,
         0.6904,  2.0991,  9.4458,  6.1120,  0.2866,  0.6747,  3.9209,  0.9991,
         1.1113,  0.3863,  0.5693,  2.2836,  2.5037, 18.8916,  5.0685,  3.3517,
         2.5037,  3.5222,  7.9926,  0.9035,  0.5118,  3.3517,  2.0991,  0.2878,
         0.7842, 10.9373,  6.4940,  4.5176,  0.3855,  0.3799,  0.5182, 18.8916,
        34.6346,  2.3090,  0.3820,  0.5182,  0.5118,  1.1675,  2.0575,  0.5274,
         1.0443,  3.8483,  1.8070,  1.0237, 23.0898,  0.3827,  0.2843,  0.2906,
         0.5106,  0.5805,  9.4458, 29.6868,  0.3813,  0.2851,  2.2588,  0.5081,
         0.3813, 17.3173,  0.3834,  0.6927,  0.5118,  3.0560,  1.0187,  0.9195,
         0.3834,  5.4686, 29.6868, 41.5616, 18.8916, 23.0898,  9.4458,  0.2843,
         3.7109, 34.6346,  1.4431,  0.3813,  0.5805,  1.0237,  0.2923,  0.3792,
         0.7754,  0.3799,  0.5693, 29.6868,  0.5157,  0.7668,  0.7584,  0.3863,
        15.9852,  4.1562, 18.8916, 18.8916, 51.9520,  5.4686,  9.0351,  7.6966,
         3.7783,  0.2855,  0.5144,  2.6988,  0.5756,  5.6164,  1.2296,  1.0495,
         0.5741,  1.6759,  0.3813,  1.3582,  0.4019,  4.2410,  0.6950,  0.3813,
         0.5106,  0.7021,  1.0137,  9.0351,  0.2870, 51.9520, 10.9373, 51.9520,
         3.7109,  4.1562,  3.9963,  7.1658,  0.9195,  5.6164,  0.7612, 18.8916,
         0.6769, 34.6346,  4.6180,  0.5709,  8.3123,  4.4214,  0.2851,  1.7761,
         0.3813,  4.1562,  0.7640, 25.9760,  1.7611, 12.2240, 41.5616,  3.5222,
        25.9760,  0.5274, 10.3904, 14.8434,  0.5106,  1.0602,  7.9926,  0.7640,
        13.8539,  1.2296,  2.7343,  2.2107, 15.9852,  9.4458,  0.7932,  0.7725,
        41.5616, 25.9760,  3.1016,  4.6180,  0.5118,  8.3123,  4.4214,  1.8892,
         0.3921,  2.1205,  5.3284,  1.2828, 29.6868,  0.2858,  0.5068, 51.9520,
        29.6868,  0.3834,  0.5131,  0.5106,  0.5081,  0.7754,  0.2855,  1.9421,
         1.4233, 12.9880,  0.6950, 20.7808,  4.6180,  2.6305,  0.2858, 34.6346,
         1.3947,  5.9374,  0.3877,  4.2410, 41.5616,  1.0602,  2.1205,  2.0575,
         0.3820,  0.5709, 29.6868,  0.3841,  1.3152,  0.5118, 41.5616,  5.7724,
         0.6881, 12.9880, 15.9852,  0.3820,  7.6966,  0.9711,  0.3813,  0.7697,
         0.3820,  2.5037, 18.8916, 10.9373,  6.2972, 29.6868,  5.6164,  1.5168,
         2.2345,  1.0187, 34.6346, 41.5616,  0.3792, 14.8434,  0.5261,  4.7229,
         3.1970,  6.1120,  0.3841, 51.9520,  7.4217,  0.2851,  0.7266,  0.6997,
        29.6868,  4.7229,  0.8181,  0.7044,  0.3820,  6.9269,  0.3820,  3.5222,
         0.3820,  0.7725,  0.5068,  1.0339,  0.7754,  1.2012,  9.8956,  0.2858,
         0.5741,  0.8623,  1.8892,  2.6305,  5.4686,  0.2866,  0.7612, 51.9520,
         2.7343, 20.7808,  6.4940,  0.2870,  0.6791, 12.2240,  0.3827,  0.5182,
        41.5616,  0.6769,  3.2985,  7.1658,  0.9075,  2.1423,  0.7783,  0.5741,
        29.6868,  1.0767,  0.6973,  0.5068,  0.6791,  1.2296,  0.3906,  0.6881,
         1.0288,  0.7725, 10.9373,  4.3293, 20.7808,  1.2296,  0.3834,  3.2470,
         0.5301,  2.5037,  0.5118,  1.0237, 34.6346,  4.4214,  5.3284, 41.5616,
         5.9374,  0.5068,  7.1658,  0.2866,  2.2107,  6.7035, 23.0898,  1.6363,
         0.7668,  0.6858, 17.3173,  2.5976,  0.3813,  9.8956, 23.0898,  2.5037,
         1.9065,  0.2862, 18.8916,  2.4164,  1.2749,  1.2296, 18.8916,  1.1675,
         4.5176, 10.3904, 12.9880,  1.5625,  0.9236,  0.6881,  6.4940,  0.6769,
         0.5118,  1.0443, 29.6868,  1.2012,  6.7035,  0.3806,  7.6966,  0.5118,
         7.6966,  2.5976, 29.6868,  0.7754,  2.5037,  1.8554,  0.9711, 10.3904,
         1.2370,  0.5068, 11.5449,  8.6587,  0.3841,  5.4686,  0.2870, 12.9880,
         0.2847,  0.7640,  0.2894, 41.5616,  0.6858, 51.9520, 34.6346, 41.5616,
        10.9373, 10.3904, 12.9880, 12.9880,  3.6458, 10.9373, 29.6868,  0.8023,
        34.6346,  0.5709,  0.5081,  2.0373,  1.2224,  0.3863,  1.6363,  3.1970,
         1.8390,  0.9195,  0.3834,  0.3806, 18.8916, 18.8916,  0.6950,  5.1952,
         1.6363,  0.3813,  0.8957,  1.7033,  1.8554,  0.3813,  4.7229, 20.7808,
         0.6747,  0.7901,  0.9236,  0.5157,  0.3848,  0.7932, 41.5616,  2.3349,
         3.1016,  2.5655,  0.2851,  2.5037,  0.9075,  1.4041,  1.8554,  0.3799,
        15.9852, 18.8916,  5.7724,  1.0237, 51.9520,  3.9963, 12.2240, 11.5449,
         4.8327, 41.5616, 25.9760,  1.7463,  0.5709, 25.9760,  0.2858,  1.1675,
         5.1952,  8.3123, 12.2240, 20.7808,  3.5829, 34.6346, 14.8434,  1.7914,
        41.5616,  2.7343,  1.8892,  1.2988,  7.1658,  2.5342,  0.5693,  3.1016,
         0.7021,  1.5863, 29.6868,  1.5743,  7.4217, 41.5616,  1.0657,  2.5037,
         6.2972,  1.6235, 51.9520,  9.4458,  1.8229, 10.3904,  0.3792,  2.5655,
         0.5081,  5.4686, 29.6868,  7.1658,  0.3792,  2.0575,  0.3841,  1.6109,
         0.6950,  0.3936,  1.8721,  2.9687,  0.7754, 29.6868,  0.3834, 20.7808,
         0.3799, 29.6868, 34.6346,  0.3834,  1.2296,  1.2370,  2.5037, 20.7808,
         0.5118,  0.5118,  3.1016,  5.6164,  1.0495,  1.8554,  1.3494,  3.8483,
         0.3892,  0.5182,  7.4217,  1.0237,  2.0176,  0.3806,  0.3799,  0.3936,
         0.3981,  0.5081,  0.3813,  5.6164,  0.9155,  0.6813,  2.2107,  1.5280,
         0.3799,  0.3813,  3.7109,  0.5234,  0.5118,  0.3813,  0.3855,  0.3928,
         0.6769,  2.0176,  4.4214,  4.2410,  4.2410,  0.2870, 51.9520,  0.7668,
         0.5157,  0.2847,  0.2858,  0.2858,  3.4067,  2.2345,  0.2862,  1.3582,
         3.9963,  0.5398,  0.3813, 11.5449,  2.4739,  1.3947,  2.5037,  1.6363,
        11.5449, 25.9760,  2.1875,  0.7932,  0.3855,  1.0137,  0.5118,  1.2444,
        34.6346,  5.6164,  3.8483,  2.0781,  1.9241,  0.3827,  2.7343,  0.7668,
        41.5616, 20.7808,  1.5985,  3.9963,  1.0390,  1.2444,  1.0237,  0.7754,
         0.5182,  0.5157,  1.2370, 10.9373,  4.4214, 25.9760,  1.8390,  0.5288,
        11.5449, 34.6346,  1.0237, 41.5616,  1.7174,  3.9209, 14.8434, 51.9520,
         0.9155,  1.0995,  1.2444,  9.8956,  0.7668,  0.6997,  0.3806,  0.5068,
         1.5863,  0.7697, 18.8916, 41.5616,  0.2851,  0.5709,  4.5176,  0.3813,
        41.5616,  0.5068,  3.1016,  1.1609,  1.0288, 14.8434, 34.6346,  0.5756,
         9.8956,  0.7640,  4.3293, 20.7808,  1.0137, 12.2240,  3.8483, 29.6868,
        51.9520,  2.1647,  0.2843, 51.9520,  0.6881,  8.3123, 25.9760,  0.7369,
        29.6868], device='cuda:0')
Shape of class weights tensor: torch.Size([713])

**Reasoning**:
To apply cost-sensitive learning, I will re-instantiate the `nn.CrossEntropyLoss` criterion with the previously calculated `class_weights_tensor` to properly weight the loss contribution of each class during training.

In [ ]:
import torch.nn as nn

# 3. Re-instantiate the nn.CrossEntropyLoss criterion with the class weights
criterion_weighted = nn.CrossEntropyLoss(weight=class_weights_tensor)

print("Weighted CrossEntropyLoss criterion initialized.")

Weighted CrossEntropyLoss criterion initialized.

In [ ]:
import torch.optim as optim

# 1. Initialize a new model_weighted using the same architecture and hyperparameters as the new_model
# Reuse VOCAB_SIZE, OUTPUT_DIM, MAX_SEQ_LEN from previous steps
model_weighted = SymptomClassifier(
    VOCAB_SIZE,
    NEW_EMBEDDING_DIM,
    NEW_HIDDEN_DIM,
    OUTPUT_DIM,
    MAX_SEQ_LEN,
    NEW_DROPOUT_PROB
)

# 2. Move model_weighted to the appropriate device
model_weighted.to(device)
print(f'Weighted model moved to device: {device}')
print(f'The weighted model has {count_parameters(model_weighted):,} trainable parameters.')

# 3. Re-initialize an Adam optimizer (optimizer_weighted) for model_weighted
optimizer_weighted = optim.Adam(model_weighted.parameters(), lr=NEW_LEARNING_RATE)

print("Weighted model and optimizer initialized successfully.")

Weighted model moved to device: cuda
The weighted model has 2,024,649 trainable parameters.
Weighted model and optimizer initialized successfully.

**Reasoning**:
To implement cost-sensitive learning, I will modify the training loop to use the `criterion_weighted` loss function, train the `model_weighted` for the specified number of epochs, store the training and validation metrics, and then evaluate its performance on the test set, including a classification report to highlight improvements in low-support classes.

In [ ]:
train_losses_history_weighted = []
val_losses_history_weighted = []
train_accuracies_history_weighted = []
val_accuracies_history_weighted = []

print("Starting training with weighted loss...")

for epoch in range(NEW_N_EPOCHS):
    # 4. Modify the training loop to use criterion_weighted
    train_loss_weighted, train_acc_weighted = train(model_weighted, train_loader_tuned, optimizer_weighted, criterion_weighted, device)
    val_loss_weighted, val_acc_weighted = evaluate(model_weighted, val_loader_tuned, criterion_weighted, device)

    # 6. Store the training and validation metrics
    train_losses_history_weighted.append(train_loss_weighted)
    val_losses_history_weighted.append(val_loss_weighted)
    train_accuracies_history_weighted.append(train_acc_weighted)
    val_accuracies_history_weighted.append(val_acc_weighted)

    print(f'Epoch: {epoch+1:02}')
    print(f'\tTrain Loss: {train_loss_weighted:.3f} | Train Acc: {train_acc_weighted*100:.2f}%')
    print(f'\tVal. Loss: {val_loss_weighted:.3f} | Val. Acc: {val_acc_weighted*100:.2f}%')

print("Training with weighted loss complete.")

# 7. After training, evaluate model_weighted on the test_loader_tuned
y_true_weighted, y_pred_weighted = get_predictions_and_labels(model_weighted, test_loader_tuned, device)

print("\nEvaluating model performance on the test set with weighted loss...")

overall_weighted_test_accuracy = accuracy_score(y_true_weighted, y_pred_weighted)
print(f"\nOverall Weighted Test Accuracy: {overall_weighted_test_accuracy:.4f}")

# 8. Generate and print a classification report
print("\nClassification Report (Weighted Model):")
print(classification_report(y_true_weighted, y_pred_weighted, target_names=target_names, zero_division=0))

# 9. Compare the performance metrics (especially for low-support classes)
print("\n--- Performance Comparison (Weighted vs. Tuned Unweighted) ---")
print(f"Tuned Unweighted Model Test Accuracy: {accuracy_tuned:.4f}")
print(f"Weighted Model Test Accuracy: {overall_weighted_test_accuracy:.4f}")
print("Review the classification reports above for detailed class-wise comparison, especially for low-support classes.")

Starting training with weighted loss...
Epoch: 01
	Train Loss: 4.409 | Train Acc: 39.97%
	Val. Loss: 2.286 | Val. Acc: 72.82%
Epoch: 02
	Train Loss: 1.604 | Train Acc: 72.32%
	Val. Loss: 0.943 | Val. Acc: 81.03%
Epoch: 03
	Train Loss: 0.838 | Train Acc: 79.28%
	Val. Loss: 0.612 | Val. Acc: 83.57%
Epoch: 04
	Train Loss: 0.601 | Train Acc: 81.72%
	Val. Loss: 0.497 | Val. Acc: 84.41%
Epoch: 05
	Train Loss: 0.497 | Train Acc: 82.91%
	Val. Loss: 0.453 | Val. Acc: 84.86%
Epoch: 06
	Train Loss: 0.442 | Train Acc: 83.78%
	Val. Loss: 0.416 | Val. Acc: 85.18%
Epoch: 07
	Train Loss: 0.407 | Train Acc: 84.26%
	Val. Loss: 0.396 | Val. Acc: 85.34%
Epoch: 08
	Train Loss: 0.384 | Train Acc: 84.62%
	Val. Loss: 0.387 | Val. Acc: 85.39%
Epoch: 09
	Train Loss: 0.367 | Train Acc: 84.93%
	Val. Loss: 0.390 | Val. Acc: 85.45%
Epoch: 10
	Train Loss: 0.350 | Train Acc: 85.27%
	Val. Loss: 0.380 | Val. Acc: 85.54%
Epoch: 11
	Train Loss: 0.341 | Train Acc: 85.57%
	Val. Loss: 0.373 | Val. Acc: 85.59%
Epoch: 12
	Train Loss: 0.332 | Train Acc: 85.59%
	Val. Loss: 0.370 | Val. Acc: 85.62%
Epoch: 13
	Train Loss: 0.322 | Train Acc: 85.79%
	Val. Loss: 0.375 | Val. Acc: 85.56%
Epoch: 14
	Train Loss: 0.319 | Train Acc: 85.95%
	Val. Loss: 0.371 | Val. Acc: 85.67%
Epoch: 15
	Train Loss: 0.308 | Train Acc: 86.11%
	Val. Loss: 0.363 | Val. Acc: 85.63%
Epoch: 16
	Train Loss: 0.304 | Train Acc: 86.25%
	Val. Loss: 0.368 | Val. Acc: 85.65%
Epoch: 17
	Train Loss: 0.300 | Train Acc: 86.43%
	Val. Loss: 0.370 | Val. Acc: 85.62%
Epoch: 18
	Train Loss: 0.293 | Train Acc: 86.57%
	Val. Loss: 0.370 | Val. Acc: 85.59%
Epoch: 19
	Train Loss: 0.288 | Train Acc: 86.71%
	Val. Loss: 0.369 | Val. Acc: 85.58%
Epoch: 20
	Train Loss: 0.285 | Train Acc: 86.72%
	Val. Loss: 0.366 | Val. Acc: 85.85%
Epoch: 21
	Train Loss: 0.283 | Train Acc: 86.93%
	Val. Loss: 0.368 | Val. Acc: 85.63%
Epoch: 22
	Train Loss: 0.277 | Train Acc: 86.96%
	Val. Loss: 0.370 | Val. Acc: 85.67%
Epoch: 23
	Train Loss: 0.273 | Train Acc: 87.00%
	Val. Loss: 0.369 | Val. Acc: 85.62%
Epoch: 24
	Train Loss: 0.268 | Train Acc: 87.25%
	Val. Loss: 0.370 | Val. Acc: 85.58%
Epoch: 25
	Train Loss: 0.268 | Train Acc: 87.28%
	Val. Loss: 0.370 | Val. Acc: 85.65%
Epoch: 26
	Train Loss: 0.266 | Train Acc: 87.22%
	Val. Loss: 0.371 | Val. Acc: 85.73%
Epoch: 27
	Train Loss: 0.263 | Train Acc: 87.37%
	Val. Loss: 0.372 | Val. Acc: 85.64%
Epoch: 28
	Train Loss: 0.258 | Train Acc: 87.55%
	Val. Loss: 0.366 | Val. Acc: 85.67%
Epoch: 29
	Train Loss: 0.257 | Train Acc: 87.58%
	Val. Loss: 0.374 | Val. Acc: 85.68%
Epoch: 30
	Train Loss: 0.257 | Train Acc: 87.56%
	Val. Loss: 0.375 | Val. Acc: 85.65%
Epoch: 31
	Train Loss: 0.255 | Train Acc: 87.71%
	Val. Loss: 0.373 | Val. Acc: 85.69%
Epoch: 32
	Train Loss: 0.248 | Train Acc: 87.76%
	Val. Loss: 0.375 | Val. Acc: 85.63%
Epoch: 33
	Train Loss: 0.251 | Train Acc: 87.76%
	Val. Loss: 0.372 | Val. Acc: 85.52%
Epoch: 34
	Train Loss: 0.243 | Train Acc: 87.88%
	Val. Loss: 0.380 | Val. Acc: 85.53%
Epoch: 35
	Train Loss: 0.244 | Train Acc: 87.89%
	Val. Loss: 0.380 | Val. Acc: 85.57%
Training with weighted loss complete.

Evaluating model performance on the test set with weighted loss...

Overall Weighted Test Accuracy: 0.8549

Classification Report (Weighted Model):
                                                          precision    recall  f1-score   support

                                            Rare Disease       0.62      0.61      0.62        33
                               abdominal aortic aneurysm       0.90      1.00      0.95        28
                                        abdominal hernia       0.93      0.99      0.96        81
                                         abscess of nose       0.63      0.90      0.74        58
                                     abscess of the lung       1.00      1.00      1.00         4
                                  abscess of the pharynx       0.82      0.93      0.87        68
                                    acanthosis nigricans       0.38      0.50      0.43         6
                                               acariasis       0.50      0.71      0.59         7
                                               achalasia       0.75      0.88      0.81        17
                                                    acne       0.63      0.81      0.71        99
                                       actinic keratosis       0.80      0.76      0.78       182
                                     acute bronchiolitis       0.97      0.88      0.92       241
                                        acute bronchitis       0.83      0.66      0.74       243
                                      acute bronchospasm       0.69      0.70      0.69       181
                   acute fatty liver of pregnancy (aflp)       0.67      1.00      0.80         2
                                          acute glaucoma       0.27      0.45      0.34        42
                                     acute kidney injury       0.99      0.96      0.97       182
                                      acute otitis media       0.71      0.91      0.80       137
                                      acute pancreatitis       0.93      0.85      0.89       241
              acute respiratory distress syndrome (ards)       0.83      0.94      0.88        90
                                         acute sinusitis       0.79      0.85      0.82       181
                                   acute stress reaction       0.91      0.91      0.91       182
                     adhesive capsulitis of the shoulder       0.79      1.00      0.88        15
                                     adjustment reaction       0.75      0.81      0.78       101
                                         adrenal adenoma       0.78      1.00      0.88         7
                                           alcohol abuse       0.88      0.89      0.89       102
                                    alcohol intoxication       0.86      0.94      0.90        70
                                      alcohol withdrawal       0.94      0.97      0.96       133
                                 alcoholic liver disease       0.96      0.96      0.96        49
                                                 allergy       0.99      0.93      0.96       181
                                      allergy to animals       1.00      1.00      1.00         8
                                                alopecia       0.71      0.93      0.80        68
                                       alzheimer disease       0.95      0.94      0.95        67
                                               amblyopia       1.00      1.00      1.00         9
                     amyotrophic lateral sclerosis (als)       0.92      1.00      0.96        12
                                            anal fissure       0.82      0.93      0.88        45
                                            anal fistula       1.00      0.75      0.86         4
                                                  anemia       0.98      0.98      0.98        66
                    anemia due to chronic kidney disease       0.89      0.80      0.84        10
                                anemia due to malignancy       1.00      1.00      1.00         2
                               anemia of chronic disease       0.78      0.88      0.82         8
                                                  angina       0.97      0.93      0.95       181
                                  ankylosing spondylitis       0.86      0.96      0.91       121
                                                 anxiety       0.97      0.90      0.93       240
                                    aortic valve disease       0.92      0.88      0.90        90
                                                 aphakia       0.29      1.00      0.44         2
                                          aphthous ulcer       0.83      0.98      0.90        49
                                         aplastic anemia       0.93      1.00      0.97        14
                                            appendicitis       0.91      0.81      0.86       181
                                              arrhythmia       0.75      0.81      0.78        52
                                    arthritis of the hip       1.00      0.94      0.97       242
                                   ascending cholangitis       0.78      1.00      0.88        14
                                       asperger syndrome       0.82      0.87      0.84        68
                                           aspergillosis       1.00      1.00      1.00         2
                                                  asthma       0.74      0.80      0.77       181
                                             astigmatism       0.84      0.59      0.70        64
                                             atelectasis       0.69      0.55      0.61        20
                                          athlete's foot       0.71      0.80      0.75        76
                                          atonic bladder       0.71      0.71      0.71        14
                                     atrial fibrillation       0.24      0.57      0.33        14
                                          atrial flutter       0.86      0.88      0.87        48
                                 atrophic skin condition       0.72      0.81      0.76        88
                                      atrophic vaginitis       0.84      0.89      0.87        66
                        atrophy of the corpus cavernosum       0.73      0.89      0.80         9
         attention deficit hyperactivity disorder (adhd)       0.81      0.85      0.83       101
                                                  autism       0.92      0.92      0.92        90
                       autonomic nervous system disorder       0.84      0.94      0.89        17
                                      avascular necrosis       0.67      1.00      0.80         2
                                               balanitis       1.00      0.97      0.98        91
                                              bell palsy       0.93      0.94      0.93       137
                                      benign kidney cyst       0.90      0.88      0.89        41
            benign paroxysmal positional vertical (bppv)       0.98      0.96      0.97        89
                      benign prostatic hyperplasia (bph)       0.97      0.93      0.95       241
                   benign vaginal discharge (leukorrhea)       0.98      0.87      0.92       136
                                        bipolar disorder       0.58      0.74      0.65       133
                                            birth trauma       1.00      1.00      1.00         2
                                          bladder cancer       0.81      1.00      0.89        25
                                        bladder disorder       0.48      0.90      0.63        91
                                     bladder obstruction       0.95      0.87      0.91        68
                                             blepharitis       0.86      0.73      0.79       181
                                           blepharospasm       1.00      1.00      1.00         1
                                             bone cancer       0.81      1.00      0.89        17
                                           bone disorder       0.98      0.94      0.96        51
                             bone spur of the calcaneous       0.86      1.00      0.92         6
                                       brachial neuritis       0.94      0.91      0.92       181
                                            brain cancer       0.82      0.80      0.81        45
                                           breast cancer       0.50      1.00      0.67         1
                                             breast cyst       1.00      1.00      1.00         4
                             breast infection (mastitis)       1.00      0.97      0.98       100
                                            broken tooth       0.97      0.97      0.97        33
                                                  bunion       0.78      0.88      0.82         8
                                                    burn       0.77      0.91      0.83        11
                                                bursitis       0.99      0.96      0.97       242
                                                  callus       0.91      0.82      0.86       103
                               carbon monoxide poisoning       0.65      0.72      0.68        18
                                          cardiac arrest       0.84      0.93      0.88        69
                                          cardiomyopathy       0.84      0.94      0.89        62
                                  carpal tunnel syndrome       0.92      0.96      0.94       179
                                                cataract       0.80      0.69      0.74       121
                                          celiac disease       0.77      0.80      0.79        30
                          cellulitis or abscess of mouth       1.00      1.00      1.00        28
                                 central atherosclerosis       0.57      1.00      0.73         4
                central retinal artery or vein occlusion       0.54      0.93      0.68        14
                                          cerebral edema       0.78      0.86      0.82        21
                                          cerebral palsy       0.96      0.96      0.96        28
                                         cervical cancer       0.82      0.95      0.88        19
                                       cervical disorder       0.90      1.00      0.95         9
                                              cervicitis       0.80      0.96      0.87        77
                                               chalazion       0.85      0.90      0.88       136
                                              chickenpox       0.77      0.95      0.85        21
                                               chlamydia       0.71      0.97      0.82        33
                                           cholecystitis       0.89      0.77      0.83       241
                                     choledocholithiasis       0.90      0.93      0.92        88
                                           cholesteatoma       0.56      0.83      0.67         6
                           chondromalacia of the patella       0.67      0.91      0.77        11
                                         chorioretinitis       0.86      0.80      0.83        15
                                       chronic back pain       0.97      0.94      0.95       180
                                    chronic constipation       0.98      0.78      0.87       183
                                        chronic glaucoma       0.83      0.65      0.73       133
chronic inflammatory demyelinating polyneuropathy (cidp)       0.80      1.00      0.89         4
                                  chronic kidney disease       0.50      0.50      0.50         2
                                       chronic knee pain       0.65      0.67      0.66        30
            chronic obstructive pulmonary disease (copd)       0.63      0.70      0.66       181
                                    chronic otitis media       0.93      0.84      0.89       134
                                   chronic pain disorder       0.84      0.92      0.88       135
                                    chronic pancreatitis       0.90      0.95      0.93        59
                                 chronic rheumatic fever       0.81      0.88      0.85        34
                                       chronic sinusitis       0.81      0.89      0.84       131
                                               cirrhosis       0.98      0.98      0.98        66
                         coagulation (bleeding) disorder       1.00      0.89      0.94        18
                                               cold sore       0.95      0.97      0.96        38
                                           colonic polyp       0.84      0.91      0.87        68
                                       colorectal cancer       0.14      0.33      0.20         3
                                             common cold       0.86      0.86      0.86       181
                          complex regional pain syndrome       0.91      0.87      0.89       243
                                              concussion       1.00      0.96      0.98       238
                                        conduct disorder       0.92      0.88      0.90       136
                                 conductive hearing loss       0.94      0.86      0.90       120
                                 congenital heart defect       1.00      0.71      0.83         7
                        congenital malformation syndrome       1.00      1.00      1.00         3
                                          conjunctivitis       0.92      0.83      0.87       182
                           conjunctivitis due to allergy       0.95      0.86      0.91       243
                          conjunctivitis due to bacteria       0.82      0.87      0.84        31
                             conjunctivitis due to virus       0.75      0.87      0.80       136
                                      contact dermatitis       0.88      0.77      0.82       182
                                     conversion disorder       0.80      1.00      0.89         4
                                        cornea infection       0.96      0.77      0.85       181
                                        corneal abrasion       0.53      0.67      0.59       100
                                        corneal disorder       0.57      0.54      0.55       135
                                coronary atherosclerosis       0.68      0.95      0.79        22
                                     cranial nerve palsy       1.00      0.93      0.96        68
                                           crohn disease       0.72      0.76      0.74        75
                                                   croup       0.90      0.78      0.83       181
                                         crushing injury       0.71      0.77      0.74        13
                                          cryptococcosis       0.67      1.00      0.80         2
                                        cushing syndrome       1.00      0.50      0.67         2
                                      cyst of the eyelid       1.00      1.00      1.00         4
                                         cystic fibrosis       1.00      1.00      1.00         3
                                           cysticercosis       0.64      1.00      0.78         7
                                                cystitis       0.92      0.72      0.81       244
                                     de quervain disease       0.71      0.83      0.77        18
                                         decubitus ulcer       1.00      0.50      0.67         2
                              deep vein thrombosis (dvt)       0.90      0.96      0.93        48
                               degenerative disc disease       0.75      0.74      0.74       182
                                                delirium       0.96      0.87      0.91       120
                                                dementia       0.88      0.90      0.89        68
                                           dental caries       0.98      0.87      0.92       237
                                              depression       0.96      0.63      0.76       182
                          dermatitis due to sun exposure       0.79      0.76      0.78        89
                                developmental disability       0.97      0.94      0.95       182

In [ ]:
import collections

# Get all unique words from the cleaned_symptom column
all_cleaned_words = []
for text in df['cleaned_symptom']:
    all_cleaned_words.extend(text.split())

unique_cleaned_words = sorted(list(set(all_cleaned_words)))

# Identify words not present in the vocabulary
unknown_words = [word for word in unique_cleaned_words if word not in vocabulary]

print(f"Total unique words in cleaned symptoms: {len(unique_cleaned_words)}")
print(f"Number of words mapping to '<unk>' (not in vocabulary): {len(unknown_words)}")

if len(unknown_words) > 0:
    print("\nWords mapping to '<unk>':")
    # Display the first 50 unknown words for brevity
    for i, word in enumerate(unknown_words):
        if i < 50:
            print(f"- {word}")
        else:
            print(f"... (and {len(unknown_words) - 50} more)")
            break
else:
    print("\nNo words found that map to '<unk>'! All cleaned symptoms are in the vocabulary.")

Total unique words in cleaned symptoms: 328
Number of words mapping to '<unk>' (not in vocabulary): 0

No words found that map to '<unk>'! All cleaned symptoms are in the vocabulary.

In [ ]:
import pickle

# Define paths for saving
label_encoder_path = 'label_encoder.pkl'
vocabulary_path = 'vocabulary.pkl'
max_seq_len_path = 'max_seq_len.pkl'

# Save the LabelEncoder
with open(label_encoder_path, 'wb') as f:
    pickle.dump(label_encoder, f)
print(f"LabelEncoder saved to: {label_encoder_path}")

# Save the vocabulary dictionary
with open(vocabulary_path, 'wb') as f:
    pickle.dump(vocabulary, f)
print(f"Vocabulary saved to: {vocabulary_path}")

# Save MAX_SEQ_LEN
with open(max_seq_len_path, 'wb') as f:
    pickle.dump(MAX_SEQ_LEN, f)
print(f"MAX_SEQ_LEN saved to: {max_seq_len_path}")

print("All essential components (LabelEncoder, vocabulary, MAX_SEQ_LEN) saved successfully.")

LabelEncoder saved to: label_encoder.pkl
Vocabulary saved to: vocabulary.pkl
MAX_SEQ_LEN saved to: max_seq_len.pkl
All essential components (LabelEncoder, vocabulary, MAX_SEQ_LEN) saved successfully.

### Loading essential components for deployment (Example)

In [ ]:
import pickle

# Define paths for loading
label_encoder_path = 'label_encoder.pkl'
vocabulary_path = 'vocabulary.pkl'
max_seq_len_path = 'max_seq_len.pkl'

# Load the LabelEncoder
with open(label_encoder_path, 'rb') as f:
    loaded_label_encoder = pickle.load(f)
print(f"LabelEncoder loaded from: {label_encoder_path}")

# Load the vocabulary dictionary
with open(vocabulary_path, 'rb') as f:
    loaded_vocabulary = pickle.load(f)
print(f"Vocabulary loaded from: {vocabulary_path}")

# Load MAX_SEQ_LEN
with open(max_seq_len_path, 'rb') as f:
    loaded_max_seq_len = pickle.load(f)
print(f"MAX_SEQ_LEN loaded from: {max_seq_len_path}")

print("All essential components loaded successfully.")

# Example usage with loaded components
print(f"\nFirst 5 classes from loaded LabelEncoder: {loaded_label_encoder.inverse_transform([0, 1, 2, 3, 4])}")
print(f"First 5 items from loaded Vocabulary: {list(loaded_vocabulary.items())[:5]}")
print(f"Loaded MAX_SEQ_LEN: {loaded_max_seq_len}")

LabelEncoder loaded from: label_encoder.pkl
Vocabulary loaded from: vocabulary.pkl
MAX_SEQ_LEN loaded from: max_seq_len.pkl
All essential components loaded successfully.

First 5 classes from loaded LabelEncoder: ['Rare Disease' 'abdominal aortic aneurysm' 'abdominal hernia'
 'abscess of nose' 'abscess of the lung']
First 5 items from loaded Vocabulary: [('<pad>', 0), ('<unk>', 1), ('abdominal_distention', 2), ('abnormal_appearing_skin', 3), ('abnormal_breathing_sounds', 4)]
Loaded MAX_SEQ_LEN: 12

In [ ]:
# Sample input for a different condition (e.g., Arthritis) using snake_case terms
sample_symptom_arthritis = "joint_pain, joint_swelling, joint_stiffness, redness, warmth , cold ,chest pain"

print(f"Original sample: '{sample_symptom_arthritis}'")

# Make prediction using the defined function
predicted_disease_arthritis, confidence_arthritis = predict_disease(
    sample_symptom_arthritis,
    loaded_model,
    loaded_label_encoder,
    loaded_vocabulary,
    loaded_max_seq_len,
    device
)

print(f"\nInput Symptoms: '{sample_symptom_arthritis}'")
print(f"Predicted Disease: {predicted_disease_arthritis}")
print(f"Confidence: {confidence_arthritis:.4f}")

Original sample: 'joint_pain, joint_swelling, joint_stiffness, redness, warmth , cold ,chest pain'

NameError: name 'predict_disease' is not defined

# Task
Create a dedicated `predict_disease` function that takes raw symptom text, the loaded model, LabelEncoder, vocabulary, and max sequence length as input, then demonstrate its usage with a new example symptom.